<!--components/components/cookies.php-->
<!-- This markup is generated by the CookieComponent class, do not write by hand -->
<?php
//This is how to use the cookie component:

//Init component
$cookieComponent = new \WonderWp\Theme\Components\CookieComponent();

//Get markup
echo $cookieComponent->getMarkup(['force'=>true]);
?>