<!--components/components/tabs.php-->
<!-- This markup is generated by the TabsComponent class, please do not write by hand -->
<?php
//This is how to use the tabs

//Init component
$tabs = new \WonderWp\Theme\Components\TabsComponent();

//Add elements to the tabs
$tabs->addBlock('First tab','Here the content of tab 1');
$tabs->addBlock('Second tab','Here the content of tab 2');
$tabs->addBlock('Third tab','Here the content of tab 3');
$tabs->addBlock('Fourth tab','Here the content of tab 4');

//Get markup
echo $tabs->getMarkup();

?>