<!--components/atoms/breadcrumb.php-->
<!-- This markup is generated by $viewService->generateCrumbsMarkup($breadCrumbs); do not write by hand -->
<?php
/** @var \WonderWp\Theme\ThemeViewService $viewService */
$viewService = \wwp_get_theme_service(\WonderWp\APlugin\AbstractManager::$VIEWSERVICENAME);
if(is_object($viewService)){
	$breadCrumbs = array(
		['title'=>'Home','href'=>'#'],
		['title'=>'Category','href'=>'#'],
		['title'=>'Page','href'=>''],

	);
	echo $viewService->generateCrumbsMarkup($breadCrumbs);
}
?>