<!--components/atoms/breadcrumb.php-->
<!-- This markup is generated by the BreadCrumbComponent class, please do not write by hand -->
<?php
//This is how to use the breadcrumb

//Init component
$breadCrumb = new \WonderWp\Theme\Core\Component\BreadCrumbComponent();

//Add elements to the breadcrumb
echo $breadCrumb->setCrumbs([
        ['title' => 'Home', 'href' => '#'],
        ['title' => 'Category', 'href' => '#'],
        ['title' => 'Page', 'href' => '']
    ]
)->getMarkup(); //Get Markup

?>
