<?php
$default = array(
	'eg-start-item' => array(
		'id' => '-1',
		'name' => 'eg-start-item',
		'default' => 'true',
		'settings' => json_decode('{"source":"icon","source-post":"title","source-event":"event_start_date","source-woocommerce":"wc_regular_price_from","source-icon":"eg-icon-search","source-text":"","enable-hover":"true","font-size":"16","line-height":"22","color":"#ffffff","0":"Default","font-family":"","font-weight":"400","text-decoration":"none","font-style":"false","text-transform":"none","display":"inline-block","text-align":"center","float":"none","clear":"none","margin":["0","0","0","0"],"padding":["17","17","17","17"],"background-color":"#ffffff","bg-alpha":"0","background-size":"cover","background-size-x":"100","background-size-y":"100","background-repeat":"no-repeat","shadow-color":"#000000","shadow-alpha":"100","box-shadow":["0","0","0","0"],"border":["2","2","2","2"],"border-radius":["60","60","60","60"],"border-radius-unit":"px","border-color":"#ffffff","border-style":"solid","font-size-hover":"16","line-height-hover":"22","color-hover":"#e33a0c","font-family-hover":"","font-weight-hover":"400","text-decoration-hover":"none","font-style-hover":"false","text-transform-hover":"none","background-color-hover":"#ffffff","bg-alpha-hover":"100","background-size-hover":"cover","background-size-x-hover":"100","background-size-y-hover":"100","background-repeat-hover":"no-repeat","shadow-color-hover":"#000000","shadow-alpha-hover":"100","box-shadow-hover":["0","0","0","0"],"border-hover":["2","2","2","2"],"border-radius-hover":["60","60","60","60"],"border-radius-unit-hover":"px","border-color-hover":"#ffffff","border-style-hover":"solid","hideunder":"0","transition":"falldown","delay":"10","link-type":"none","url-link":"","javascript-link":""}', true)
		),
'tmp-dark-icon' => array(
		'id' => '-1',
		'name' => 'Dark Icon',
		'default' => 'true',
		'settings' => json_decode('{"source":"icon","source-post":"title","source-woocommerce":"wc_full_price","source-separate":",","source-meta":"","limit-type":"none","limit-num":"10","source-icon":"eg-icon-search","source-text":"","enable-hover":"true","font-size":"16","line-height":"22","color":"#ffffff","0":"Default","font-family":"\"Open Sans\"","font-weight":"400","text-decoration":"none","font-style":"false","text-transform":"none","position":"relative","align":"t_l","absolute-unit":"px","top-bottom":"0","left-right":"0","display":"inline-block","text-align":"center","float":"none","clear":"none","margin":["0","10","0","0"],"padding":["17","17","17","17"],"background-color":"#ffffff","bg-alpha":"15","shadow-color":"#000000","shadow-alpha":"100","box-shadow":["0","0","0","0"],"border":["0","0","0","0"],"border-radius":["60","60","60","60"],"border-radius-unit":"px","border-color":"#ffffff","border-style":"solid","font-size-hover":"16","line-height-hover":"22","color-hover":"#ffffff","font-family-hover":"","font-weight-hover":"400","text-decoration-hover":"none","font-style-hover":"false","text-transform-hover":"none","background-color-hover":"#000000","bg-alpha-hover":"50","shadow-color-hover":"#000000","shadow-alpha-hover":"100","box-shadow-hover":["0","0","0","0"],"border-hover":["0","0","0","0"],"border-radius-hover":["60","60","60","60"],"border-radius-unit-hover":"px","border-color-hover":"#ffffff","border-style-hover":"solid","hideunder":"0","hide-on-video":"false","show-on-sale":"false","show-if-featured":"false","transition":"falldown","transition-type":"","delay":"10","link-type":"lightbox","url-link":"","meta-link":"","javascript-link":"","tag-type":"div","force-important":"true","attribute":"","class":"","rel":""}', true)
		),
'tmp-light-icon' => array(
		'id' => '-1',
		'name' => 'Light Icon',
		'default' => 'true',
		'settings' => json_decode('{"source":"icon","source-post":"title","source-woocommerce":"wc_full_price","source-separate":",","source-meta":"","limit-type":"none","limit-num":"10","source-icon":"eg-icon-search","source-text":"","enable-hover":"true","font-size":"16","line-height":"22","color":"#ffffff","0":"Default","font-family":"","font-weight":"400","text-decoration":"none","font-style":"false","text-transform":"none","position":"relative","align":"t_l","absolute-unit":"px","top-bottom":"0","left-right":"0","display":"inline-block","text-align":"center","float":"none","clear":"none","margin":["0","10","0","0"],"padding":["17","17","17","17"],"background-color":"#ffffff","bg-alpha":"0","shadow-color":"#000000","shadow-alpha":"100","box-shadow":["0","0","0","0"],"border":["2","2","2","2"],"border-radius":["60","60","60","60"],"border-radius-unit":"px","border-color":"#ffffff","border-style":"solid","font-size-hover":"16","line-height-hover":"22","color-hover":"#000000","font-family-hover":"","font-weight-hover":"400","text-decoration-hover":"none","font-style-hover":"false","text-transform-hover":"none","background-color-hover":"#ffffff","bg-alpha-hover":"100","shadow-color-hover":"#000000","shadow-alpha-hover":"100","box-shadow-hover":["0","0","0","0"],"border-hover":["2","2","2","2"],"border-radius-hover":["60","60","60","60"],"border-radius-unit-hover":"px","border-color-hover":"#ffffff","border-style-hover":"solid","hideunder":"0","hide-on-video":"false","show-on-sale":"false","show-if-featured":"false","transition":"slideright","transition-type":"","delay":"10","link-type":"lightbox","url-link":"","meta-link":"","javascript-link":"","tag-type":"div","force-important":"true","attribute":"","class":"","rel":""}', true)
		),
'tmp-dark-light-icon' => array(
		'id' => '-1',
		'name' => 'Dark Light Icon',
		'default' => 'true',
		'settings' => json_decode('{"source":"icon","source-post":"title","source-woocommerce":"wc_full_price","source-separate":",","source-meta":"","limit-type":"none","limit-num":"10","source-icon":"eg-icon-search","source-text":"","enable-hover":"true","font-size":"16","line-height":"22","color":"#000000","0":"Default","font-family":"","font-weight":"400","text-decoration":"none","font-style":"false","text-transform":"none","position":"relative","align":"t_l","absolute-unit":"px","top-bottom":"0","left-right":"0","display":"inline-block","text-align":"center","float":"none","clear":"none","margin":["0","10","0","0"],"padding":["17","17","17","17"],"background-color":"#f5f5f5","bg-alpha":"100","shadow-color":"#000000","shadow-alpha":"100","box-shadow":["0","0","0","0"],"border":["0","0","0","0"],"border-radius":["60","60","60","60"],"border-radius-unit":"px","border-color":"#ffffff","border-style":"solid","font-size-hover":"16","line-height-hover":"22","color-hover":"#000000","font-family-hover":"","font-weight-hover":"400","text-decoration-hover":"none","font-style-hover":"false","text-transform-hover":"none","background-color-hover":"#eeeeee","bg-alpha-hover":"100","shadow-color-hover":"#000000","shadow-alpha-hover":"100","box-shadow-hover":["0","0","0","0"],"border-hover":["0","0","0","0"],"border-radius-hover":["60","60","60","60"],"border-radius-unit-hover":"px","border-color-hover":"#ffffff","border-style-hover":"solid","hideunder":"0","hide-on-video":"false","show-on-sale":"false","show-if-featured":"false","transition":"zoomback","transition-type":"","delay":"5","link-type":"lightbox","url-link":"","meta-link":"","javascript-link":"","tag-type":"div","force-important":"false","attribute":"","class":"","rel":""}', true)
		),
'tmp-simple-icon' => array(
		'id' => '-1',
		'name' => 'Simple Icon',
		'default' => 'true',
		'settings' => json_decode('{"source":"icon","source-post":"title","source-woocommerce":"wc_full_price","source-separate":",","source-meta":"","limit-type":"none","limit-num":"10","source-icon":"eg-icon-search","source-text":"","enable-hover":"true","font-size":"24","line-height":"22","color":"#ffffff","0":"Default","font-family":"","font-weight":"400","text-decoration":"none","font-style":"false","text-transform":"none","position":"relative","align":"t_l","absolute-unit":"px","top-bottom":"0","left-right":"0","display":"inline-block","text-align":"center","float":"none","clear":"none","margin":["0","10","0","10"],"padding":["0","0","0","0"],"background-color":"#2d3039","bg-alpha":"0","shadow-color":"#000000","shadow-alpha":"100","box-shadow":["0","0","0","0"],"border":["0","0","0","0"],"border-radius":["0","0","0","0"],"border-radius-unit":"px","border-color":"#ffffff","border-style":"solid","font-size-hover":"24","line-height-hover":"22","color-hover":"#ffffff","font-family-hover":"","font-weight-hover":"400","text-decoration-hover":"none","font-style-hover":"false","text-transform-hover":"none","background-color-hover":"#2d3039","bg-alpha-hover":"0","shadow-color-hover":"#000000","shadow-alpha-hover":"100","box-shadow-hover":["0","0","0","0"],"border-hover":["0","0","0","0"],"border-radius-hover":["60","60","60","60"],"border-radius-unit-hover":"px","border-color-hover":"#ffffff","border-style-hover":"solid","hideunder":"0","hide-on-video":"false","show-on-sale":"false","show-if-featured":"false","transition":"zoomfront","transition-type":"","delay":"30","link-type":"lightbox","url-link":"","meta-link":"","javascript-link":"","tag-type":"div","force-important":"false","attribute":"","class":"","rel":""}', true)
		),
'tmp-corner-icon' => array(
		'id' => '-1',
		'name' => 'Corner Icon',
		'default' => 'true',
		'settings' => json_decode('{"source":"icon","source-post":"title","source-woocommerce":"wc_full_price","source-separate":",","source-meta":"","limit-type":"none","limit-num":"10","source-icon":"eg-icon-plus","source-text":"","enable-hover":"true","font-size":"20","line-height":"27","color":"#ffffff","0":"Default","font-family":"\"Raleway\"","font-weight":"800","text-decoration":"none","font-style":"false","text-transform":"none","position":"relative","align":"t_l","absolute-unit":"px","top-bottom":"0","left-right":"0","display":"inline-block","text-align":"center","float":"none","clear":"none","margin":["0","0","0","0"],"padding":["17","17","17","17"],"background-color":"#ffffff","bg-alpha":"0","shadow-color":"#000000","shadow-alpha":"100","box-shadow":["0","0","0","0"],"border":["2","2","2","2"],"border-radius":["0","60","60","60"],"border-radius-unit":"px","border-color":"#ffffff","border-style":"solid","font-size-hover":"20","line-height-hover":"27","color-hover":"#ffffff","font-family-hover":"","font-weight-hover":"400","text-decoration-hover":"none","font-style-hover":"false","text-transform-hover":"none","background-color-hover":"#000000","bg-alpha-hover":"15","shadow-color-hover":"#000000","shadow-alpha-hover":"100","box-shadow-hover":["0","0","0","0"],"border-hover":["2","2","2","2"],"border-radius-hover":["60","60","0","60"],"border-radius-unit-hover":"px","border-color-hover":"#ffffff","border-style-hover":"solid","hideunder":"0","hide-on-video":"false","show-on-sale":"false","show-if-featured":"false","transition":"rotatescale","transition-type":"","delay":"5","link-type":"post","url-link":"","meta-link":"","javascript-link":"","tag-type":"div","force-important":"false","attribute":"","class":"","rel":""}', true)
		),
'tmp-box-icon-light' => array(
		'id' => '-1',
		'name' => 'Box Icon Light',
		'default' => 'true',
		'settings' => json_decode('{"source":"icon","source-post":"title","source-woocommerce":"wc_full_price","source-separate":",","source-meta":"","limit-type":"none","limit-num":"10","source-icon":"eg-icon-link-ext","source-text":"","enable-hover":"true","font-size":"16","line-height":"22","color":"#ffffff","0":"Default","font-family":"","font-weight":"400","text-decoration":"none","font-style":"false","text-transform":"none","position":"relative","align":"t_l","absolute-unit":"px","top-bottom":"0","left-right":"0","display":"inline-block","text-align":"center","float":"left","clear":"right","margin":["0","0","0","0"],"padding":["13","13","13","13"],"background-color":"#000000","bg-alpha":"15","shadow-color":"#000000","shadow-alpha":"100","box-shadow":["0","0","0","0"],"border":["0","0","0","0"],"border-radius":["0","0","0","0"],"border-radius-unit":"px","border-color":"#ffffff","border-style":"solid","font-size-hover":"16","line-height-hover":"22","color-hover":"#ffffff","font-family-hover":"","font-weight-hover":"400","text-decoration-hover":"none","font-style-hover":"false","text-transform-hover":"none","background-color-hover":"#000000","bg-alpha-hover":"40","shadow-color-hover":"#000000","shadow-alpha-hover":"100","box-shadow-hover":["0","0","0","0"],"border-hover":["0","0","0","0"],"border-radius-hover":["0","0","0","0"],"border-radius-unit-hover":"px","border-color-hover":"#ffffff","border-style-hover":"solid","hideunder":"0","hide-on-video":"false","show-on-sale":"false","show-if-featured":"false","transition":"rollleft","transition-type":"","delay":"30","link-type":"post","url-link":"","meta-link":"","javascript-link":"","tag-type":"div","force-important":"false","attribute":"","class":"","rel":""}', true)
		),
'tmp-boxed-light-icon' => array(
		'id' => '-1',
		'name' => 'Boxed Light Icon',
		'default' => 'true',
		'settings' => json_decode('{"source":"icon","source-post":"title","source-woocommerce":"wc_full_price","source-separate":",","source-meta":"","limit-type":"none","limit-num":"10","source-icon":"eg-icon-videocam","source-text":"","enable-hover":"true","font-size":"16","line-height":"22","color":"#ffffff","0":"Default","font-family":"","font-weight":"400","text-decoration":"none","font-style":"false","text-transform":"none","position":"relative","align":"t_l","absolute-unit":"px","top-bottom":"0","left-right":"0","display":"inline-block","text-align":"center","float":"none","clear":"none","margin":["0","0","1","0"],"padding":["13","13","13","13"],"background-color":"#ffffff","bg-alpha":"15","shadow-color":"#000000","shadow-alpha":"100","box-shadow":["0","0","0","0"],"border":["0","0","0","0"],"border-radius":["0","0","0","0"],"border-radius-unit":"px","border-color":"#ffffff","border-style":"solid","font-size-hover":"16","line-height-hover":"22","color-hover":"#ffffff","font-family-hover":"","font-weight-hover":"400","text-decoration-hover":"none","font-style-hover":"false","text-transform-hover":"none","background-color-hover":"#000000","bg-alpha-hover":"25","shadow-color-hover":"#000000","shadow-alpha-hover":"100","box-shadow-hover":["0","0","0","0"],"border-hover":["0","0","0","0"],"border-radius-hover":["0","0","0","0"],"border-radius-unit-hover":"px","border-color-hover":"#ffffff","border-style-hover":"solid","hideunder":"0","hide-on-video":"false","show-on-sale":"false","show-if-featured":"false","transition":"slideup","transition-type":"","delay":"20","link-type":"embedded_video","url-link":"","meta-link":"","javascript-link":"","tag-type":"div","force-important":"false","attribute":"","class":"","rel":""}', true)
		),
'tmp-small-icon' => array(
		'id' => '-1',
		'name' => 'Small Icon',
		'default' => 'true',
		'settings' => json_decode('{"source":"icon","source-post":"title","source-woocommerce":"wc_full_price","source-separate":",","source-meta":"","limit-type":"none","limit-num":"10","source-icon":"eg-icon-search","source-text":"","enable-hover":"false","font-size":"17","line-height":"22","color":"#ffffff","0":"Default","font-family":"","font-weight":"200","text-decoration":"none","font-style":"false","text-transform":"none","position":"relative","align":"t_l","absolute-unit":"px","top-bottom":"0","left-right":"0","display":"inline-block","text-align":"center","float":"none","clear":"none","margin":["0","0","0","0"],"padding":["0","0","0","0"],"background-color":"#ffffff","bg-alpha":"0","shadow-color":"#000000","shadow-alpha":"100","box-shadow":["0","0","0","0"],"border":["0","0","0","0"],"border-radius":["0","0","0","0"],"border-radius-unit":"px","border-color":"#ffffff","border-style":"solid","font-size-hover":"16","line-height-hover":"7","color-hover":"#e33a0c","font-family-hover":"","font-weight-hover":"400","text-decoration-hover":"none","font-style-hover":"false","text-transform-hover":"none","background-color-hover":"#ffffff","bg-alpha-hover":"100","shadow-color-hover":"#000000","shadow-alpha-hover":"100","box-shadow-hover":["0","0","0","0"],"border-hover":["2","2","2","2"],"border-radius-hover":["60","60","60","60"],"border-radius-unit-hover":"px","border-color-hover":"#ffffff","border-style-hover":"solid","hideunder":"0","hide-on-video":"true","show-on-sale":"false","show-if-featured":"false","transition":"slide","transition-type":"","delay":"35","link-type":"lightbox","url-link":"","meta-link":"","javascript-link":"","tag-type":"div","force-important":"true","attribute":"","class":"","rel":""}', true)
		),
'tmp-red-icon' => array(
		'id' => '-1',
		'name' => 'Red Icon',
		'default' => 'true',
		'settings' => json_decode('{"source":"icon","source-post":"title","source-woocommerce":"wc_full_price","source-separate":",","source-meta":"","limit-type":"none","limit-num":"10","source-icon":"eg-icon-search","source-text":"","enable-hover":"true","font-size":"16","line-height":"22","color":"#ffffff","0":"Default","font-family":"","font-weight":"400","text-decoration":"none","font-style":"false","text-transform":"none","position":"relative","align":"t_l","absolute-unit":"px","top-bottom":"0","left-right":"0","display":"inline-block","text-align":"center","float":"none","clear":"none","margin":["0","0","0","0"],"padding":["17","17","17","17"],"background-color":"#e33a0c","bg-alpha":"100","shadow-color":"#000000","shadow-alpha":"100","box-shadow":["0","0","0","0"],"border":["0","0","0","0"],"border-radius":["60","60","60","60"],"border-radius-unit":"px","border-color":"#ffffff","border-style":"solid","font-size-hover":"16","line-height-hover":"22","color-hover":"#ffffff","font-family-hover":"","font-weight-hover":"400","text-decoration-hover":"none","font-style-hover":"false","text-transform-hover":"none","background-color-hover":"#000000","bg-alpha-hover":"100","shadow-color-hover":"#000000","shadow-alpha-hover":"100","box-shadow-hover":["0","0","0","0"],"border-hover":["0","0","0","0"],"border-radius-hover":["60","60","60","60"],"border-radius-unit-hover":"px","border-color-hover":"#ffffff","border-style-hover":"solid","hideunder":"0","hide-on-video":"false","show-on-sale":"false","show-if-featured":"false","transition":"slide","transition-type":"","delay":"10","link-type":"lightbox","url-link":"","meta-link":"","javascript-link":"","tag-type":"div","force-important":"true","attribute":"","class":"","rel":""}', true)
		),
'tmp-white-on-light-13px' => array(
		'id' => '-1',
		'name' => 'White on Light 13px',
		'default' => 'true',
		'settings' => json_decode('{"source":"post","source-post":"title","source-woocommerce":"wc_full_price","source-separate":",","source-meta":"","limit-type":"none","limit-num":"10","source-icon":"","source-text":"","enable-hover":"false","font-size":"13","line-height":"20","color":"#ffffff","0":"Default","font-family":"\"Open Sans\"","font-weight":"700","text-decoration":"none","font-style":"false","text-transform":"uppercase","position":"relative","align":"t_l","absolute-unit":"px","top-bottom":"0","left-right":"0","display":"inline-block","text-align":"center","float":"none","clear":"both","margin":["15","0","0","0"],"padding":["5","10","5","10"],"background-color":"#ffffff","bg-alpha":"15","shadow-color":"#000000","shadow-alpha":"100","box-shadow":["0","0","0","0"],"border":["0","0","0","0"],"border-radius":["0","0","0","0"],"border-radius-unit":"px","border-color":"transparent","border-style":"none","font-size-hover":"13","line-height-hover":"14","color-hover":"#ffffff","font-family-hover":"","font-weight-hover":"700","text-decoration-hover":"none","font-style-hover":"false","text-transform-hover":"uppercase","background-color-hover":"#ffffff","bg-alpha-hover":"15","shadow-color-hover":"#000000","shadow-alpha-hover":"100","box-shadow-hover":["0","0","0","0"],"border-hover":["0","0","0","0"],"border-radius-hover":["0","0","0","0"],"border-radius-unit-hover":"px","border-color-hover":"transparent","border-style-hover":"none","hideunder":"0","hide-on-video":"false","show-on-sale":"false","show-if-featured":"false","transition":"flipup","transition-type":"","delay":"10","link-type":"none","url-link":"","meta-link":"","javascript-link":"","tag-type":"div","force-important":"false","attribute":"","class":"","rel":""}', true)
		),
'tmp-white-capital-17px' => array(
		'id' => '-1',
		'name' => 'White Capital 17px',
		'default' => 'true',
		'settings' => json_decode('{"source":"post","source-post":"title","source-woocommerce":"wc_full_price","source-separate":",","source-meta":"","limit-type":"none","limit-num":"10","source-icon":"","source-text":"","enable-hover":"false","font-size":"17","line-height":"20","color":"#ffffff","0":"Default","font-family":"","font-weight":"800","text-decoration":"none","font-style":"false","text-transform":"uppercase","position":"relative","align":"t_l","absolute-unit":"px","top-bottom":"0","left-right":"0","display":"inline-block","text-align":"center","float":"none","clear":"both","margin":["10","0","0","0"],"padding":["0","0","0","0"],"background-color":"#ffffff","bg-alpha":"0","shadow-color":"#000000","shadow-alpha":"100","box-shadow":["0","0","0","0"],"border":["0","0","0","0"],"border-radius":["0","0","0","0"],"border-radius-unit":"px","border-color":"transparent","border-style":"none","font-size-hover":"17","line-height-hover":"14","color-hover":"#ffffff","font-family-hover":"","font-weight-hover":"700","text-decoration-hover":"none","font-style-hover":"false","text-transform-hover":"uppercase","background-color-hover":"#ffffff","bg-alpha-hover":"15","shadow-color-hover":"#000000","shadow-alpha-hover":"100","box-shadow-hover":["0","0","0","0"],"border-hover":["0","0","0","0"],"border-radius-hover":["0","0","0","0"],"border-radius-unit-hover":"px","border-color-hover":"transparent","border-style-hover":"none","hideunder":"0","hide-on-video":"false","show-on-sale":"false","show-if-featured":"false","transition":"zoomfront","transition-type":"","delay":"60","link-type":"none","url-link":"","meta-link":"","javascript-link":"","tag-type":"div","force-important":"false","attribute":"","class":"","rel":""}', true)
		),
'tmp-black-on-white-17px' => array(
		'id' => '-1',
		'name' => 'Black on White 17px',
		'default' => 'true',
		'settings' => json_decode('{"source":"post","source-post":"date","source-woocommerce":"wc_full_price","source-separate":",","source-meta":"","limit-type":"none","limit-num":"10","source-icon":"","source-text":"","enable-hover":"false","font-size":"17","line-height":"24","color":"#000000","0":"Default","font-family":"\"Raleway\"","font-weight":"800","text-decoration":"none","font-style":"false","text-transform":"capitalize","position":"relative","align":"t_l","absolute-unit":"px","top-bottom":"0","left-right":"0","display":"inline-block","text-align":"center","float":"none","clear":"both","margin":["30","0","0","0"],"padding":["3","12","4","12"],"background-color":"#ffffff","bg-alpha":"100","shadow-color":"#000000","shadow-alpha":"0","box-shadow":["0","0","0","0"],"border":["0","0","0","0"],"border-radius":["0","0","0","0"],"border-radius-unit":"px","border-color":"transparent","border-style":"none","font-size-hover":"13","line-height-hover":"14","color-hover":"#ffffff","font-family-hover":"","font-weight-hover":"300","text-decoration-hover":"none","font-style-hover":"false","text-transform-hover":"none","background-color-hover":"#ffffff","bg-alpha-hover":"20","shadow-color-hover":"#000000","shadow-alpha-hover":"100","box-shadow-hover":["0","0","0","0"],"border-hover":["0","0","0","0"],"border-radius-hover":["0","0","0","0"],"border-radius-unit-hover":"px","border-color-hover":"transparent","border-style-hover":"none","hideunder":"0","hide-on-video":"false","show-on-sale":"false","show-if-featured":"false","transition":"slidedown","transition-type":"","delay":"0","link-type":"none","url-link":"","meta-link":"","javascript-link":"","tag-type":"div","force-important":"false","attribute":"","class":"","rel":""}', true)
		),
'tmp-white-on-light-16px' => array(
		'id' => '-1',
		'name' => 'White on Light 16px',
		'default' => 'true',
		'settings' => json_decode('{"source":"post","source-post":"title","source-woocommerce":"wc_full_price","source-separate":",","source-meta":"","limit-type":"none","limit-num":"10","source-icon":"","source-text":"","enable-hover":"false","font-size":"16","line-height":"24","color":"#ffffff","0":"Default","font-family":"\"Raleway\"","font-weight":"900","text-decoration":"none","font-style":"false","text-transform":"capitalize","position":"relative","align":"t_l","absolute-unit":"px","top-bottom":"0","left-right":"0","display":"inline-block","text-align":"center","float":"none","clear":"both","margin":["0","0","0","0"],"padding":["4","12","3","12"],"background-color":"#ffffff","bg-alpha":"15","shadow-color":"#000000","shadow-alpha":"0","box-shadow":["0","0","0","0"],"border":["0","0","0","0"],"border-radius":["0","0","0","0"],"border-radius-unit":"px","border-color":"transparent","border-style":"none","font-size-hover":"13","line-height-hover":"14","color-hover":"#ffffff","font-family-hover":"","font-weight-hover":"300","text-decoration-hover":"none","font-style-hover":"false","text-transform-hover":"none","background-color-hover":"#ffffff","bg-alpha-hover":"20","shadow-color-hover":"#000000","shadow-alpha-hover":"100","box-shadow-hover":["0","0","0","0"],"border-hover":["0","0","0","0"],"border-radius-hover":["0","0","0","0"],"border-radius-unit-hover":"px","border-color-hover":"transparent","border-style-hover":"none","hideunder":"0","hide-on-video":"false","show-on-sale":"false","show-if-featured":"false","transition":"flipdown","transition-type":"out","delay":"0","link-type":"none","url-link":"","meta-link":"","javascript-link":"","tag-type":"div","force-important":"false","attribute":"","class":"","rel":""}', true)
		),
'tmp-green-button-13px' => array(
		'id' => '-1',
		'name' => 'Green Button 13px',
		'default' => 'true',
		'settings' => json_decode('{"source":"text","source-post":"title","source-woocommerce":"wc_full_price","source-separate":",","source-meta":"","limit-type":"none","limit-num":"10","source-icon":"","source-text":"Read More","enable-hover":"true","font-size":"13","line-height":"30","color":"#ffffff","0":"Default","font-family":"\"Raleway\"","font-weight":"800","text-decoration":"none","font-style":"false","text-transform":"none","position":"relative","align":"t_l","absolute-unit":"px","top-bottom":"0","left-right":"0","display":"inline-block","text-align":"center","float":"none","clear":"both","margin":["0","0","30","0"],"padding":["3","15","2","15"],"background-color":"#89af72","bg-alpha":"100","shadow-color":"#ffffff","shadow-alpha":"0","box-shadow":["0","0","0","0"],"border":["0","0","3","0"],"border-radius":["3","3","3","3"],"border-radius-unit":"px","border-color":"#617f52","border-style":"solid","font-size-hover":"13","line-height-hover":"30","color-hover":"#ffffff","font-family-hover":"\"Raleway\"","font-weight-hover":"800","text-decoration-hover":"none","font-style-hover":"false","text-transform-hover":"none","background-color-hover":"#9bc184","bg-alpha-hover":"100","shadow-color-hover":"#000000","shadow-alpha-hover":"0","box-shadow-hover":["0","0","0","0"],"border-hover":["0","0","3","0"],"border-radius-hover":["3","3","3","3"],"border-radius-unit-hover":"px","border-color-hover":"#617f52","border-style-hover":"solid","hideunder":"0","hide-on-video":"false","show-on-sale":"false","show-if-featured":"false","transition":"flipup","transition-type":"","delay":"0","link-type":"post","url-link":"","meta-link":"","javascript-link":"","tag-type":"div","force-important":"false","attribute":"","class":"","rel":""}', true)
		),
'tmp-black-18px' => array(
		'id' => '-1',
		'name' => 'Black 18px',
		'default' => 'true',
		'settings' => json_decode('{"source":"post","source-post":"title","source-woocommerce":"wc_full_price","source-separate":",","source-meta":"","limit-type":"none","limit-num":"10","source-icon":"","source-text":"","enable-hover":"false","font-size":"18","line-height":"20","color":"#000000","0":"Default","font-family":"\"Raleway\"","font-weight":"800","text-decoration":"none","font-style":"false","text-transform":"none","position":"relative","align":"t_l","absolute-unit":"px","top-bottom":"0","left-right":"0","display":"inline-block","text-align":"center","float":"none","clear":"both","margin":["15","0","0","0"],"padding":["0","0","0","0"],"background-color":"#ffffff","bg-alpha":"15","shadow-color":"#000000","shadow-alpha":"100","box-shadow":["0","0","0","0"],"border":["0","0","0","0"],"border-radius":["0","0","0","0"],"border-radius-unit":"px","border-color":"transparent","border-style":"none","font-size-hover":"18","line-height-hover":"14","color-hover":"#ffffff","font-family-hover":"","font-weight-hover":"300","text-decoration-hover":"none","font-style-hover":"false","text-transform-hover":"none","background-color-hover":"#ffffff","bg-alpha-hover":"15","shadow-color-hover":"#000000","shadow-alpha-hover":"100","box-shadow-hover":["0","0","0","0"],"border-hover":["0","0","0","0"],"border-radius-hover":["0","0","0","0"],"border-radius-unit-hover":"px","border-color-hover":"transparent","border-style-hover":"none","hideunder":"0","hide-on-video":"false","show-on-sale":"false","show-if-featured":"false","transition":"skewright","transition-type":"","delay":"15","link-type":"none","url-link":"","meta-link":"","javascript-link":"","tag-type":"div","force-important":"false","attribute":"","class":"","rel":""}', true)
		),
'tmp-black-thin-capital-12px' => array(
		'id' => '-1',
		'name' => 'Black Thin Capital 12px',
		'default' => 'true',
		'settings' => json_decode('{"source":"post","source-post":"cat_list","source-woocommerce":"wc_full_price","source-separate":", ","source-meta":"","limit-type":"none","limit-num":"10","source-icon":"","source-text":"","enable-hover":"true","font-size":"12","line-height":"20","color":"#888888","0":"Default","font-family":"\"Raleway\"","font-weight":"400","text-decoration":"none","font-style":"false","text-transform":"uppercase","position":"relative","align":"t_l","absolute-unit":"px","top-bottom":"0","left-right":"0","display":"inline-block","text-align":"center","float":"none","clear":"both","margin":["0","0","0","0"],"padding":["0","0","0","0"],"background-color":"#ffffff","bg-alpha":"0","shadow-color":"#000000","shadow-alpha":"100","box-shadow":["0","0","0","0"],"border":["0","0","0","0"],"border-radius":["0","0","0","0"],"border-radius-unit":"px","border-color":"transparent","border-style":"none","font-size-hover":"12","line-height-hover":"20","color-hover":"#000000","font-family-hover":"\"Raleway\"","font-weight-hover":"400","text-decoration-hover":"none","font-style-hover":"false","text-transform-hover":"uppercase","background-color-hover":"#ffffff","bg-alpha-hover":"0","shadow-color-hover":"#000000","shadow-alpha-hover":"100","box-shadow-hover":["0","0","0","0"],"border-hover":["0","0","0","0"],"border-radius-hover":["0","0","0","0"],"border-radius-unit-hover":"px","border-color-hover":"transparent","border-style-hover":"none","hideunder":"0","hide-on-video":"false","show-on-sale":"false","show-if-featured":"false","transition":"skewleft","transition-type":"","delay":"10","link-type":"none","url-link":"","meta-link":"","javascript-link":"","tag-type":"div","force-important":"false","attribute":"","class":"","rel":""}', true)
		),
'tmp-white-on-red-capital-12px' => array(
		'id' => '-1',
		'name' => 'White on Red Capital 12px',
		'default' => 'true',
		'settings' => json_decode('{"source":"text","source-post":"title","source-woocommerce":"wc_full_price","source-separate":",","source-meta":"","limit-type":"none","limit-num":"10","source-icon":"","source-text":"Check it Out","enable-hover":"true","font-size":"12","line-height":"24","color":"#ffffff","0":"Default","font-family":"\"Open Sans\"","font-weight":"800","text-decoration":"none","font-style":"false","text-transform":"uppercase","position":"relative","align":"t_l","absolute-unit":"px","top-bottom":"0","left-right":"0","display":"inline-block","text-align":"center","float":"none","clear":"both","margin":["0","0","0","0"],"padding":["3","10","2","10"],"background-color":"#e33a0c","bg-alpha":"100","shadow-color":"#ffffff","shadow-alpha":"0","box-shadow":["0","0","0","0"],"border":["0","0","0","0"],"border-radius":["0","0","0","0"],"border-radius-unit":"px","border-color":"#617f52","border-style":"none","font-size-hover":"12","line-height-hover":"24","color-hover":"#ffffff","font-family-hover":"\"Open Sans\"","font-weight-hover":"800","text-decoration-hover":"none","font-style-hover":"false","text-transform-hover":"uppercase","background-color-hover":"#ff4d1c","bg-alpha-hover":"100","shadow-color-hover":"#000000","shadow-alpha-hover":"0","box-shadow-hover":["0","0","0","0"],"border-hover":["0","0","0","0"],"border-radius-hover":["0","0","0","0"],"border-radius-unit-hover":"px","border-color-hover":"#617f52","border-style-hover":"none","hideunder":"0","hide-on-video":"false","show-on-sale":"false","show-if-featured":"false","transition":"slideup","transition-type":"","delay":"0","link-type":"meta","url-link":"","meta-link":"eg-demogrid-link","javascript-link":"","tag-type":"div","force-important":"true","attribute":"","class":"","rel":""}', true)
		),
'tmp-white-capital-13px' => array(
		'id' => '-1',
		'name' => 'White Capital 13px',
		'default' => 'true',
		'settings' => json_decode('{"source":"post","source-post":"title","source-woocommerce":"wc_full_price","source-separate":",","source-meta":"","limit-type":"none","limit-num":"10","source-icon":"","source-text":"","enable-hover":"false","font-size":"13","line-height":"19","color":"#ffffff","0":"Default","font-family":"","font-weight":"700","text-decoration":"none","font-style":"false","text-transform":"uppercase","position":"relative","align":"t_l","absolute-unit":"px","top-bottom":"0","left-right":"0","display":"block","text-align":"center","float":"none","clear":"both","margin":["10","0","0","0"],"padding":["0","0","0","0"],"background-color":"#ffffff","bg-alpha":"0","shadow-color":"#000000","shadow-alpha":"100","box-shadow":["0","0","0","0"],"border":["0","0","0","0"],"border-radius":["0","0","0","0"],"border-radius-unit":"px","border-color":"transparent","border-style":"none","font-size-hover":"13","line-height-hover":"14","color-hover":"#ffffff","font-family-hover":"","font-weight-hover":"700","text-decoration-hover":"none","font-style-hover":"false","text-transform-hover":"uppercase","background-color-hover":"#ffffff","bg-alpha-hover":"15","shadow-color-hover":"#000000","shadow-alpha-hover":"100","box-shadow-hover":["0","0","0","0"],"border-hover":["0","0","0","0"],"border-radius-hover":["0","0","0","0"],"border-radius-unit-hover":"px","border-color-hover":"transparent","border-style-hover":"none","hideunder":"0","hide-on-video":"false","show-on-sale":"false","show-if-featured":"false","transition":"flipdown","transition-type":"","delay":"46","link-type":"none","url-link":"","meta-link":"","javascript-link":"","tag-type":"div","force-important":"true","attribute":"","class":"","rel":""}', true)
		),
'tmp-white-thin-capital-13px' => array(
		'id' => '-1',
		'name' => 'White Thin Capital 13px',
		'default' => 'true',
		'settings' => json_decode('{"source":"post","source-post":"excerpt","source-woocommerce":"wc_full_price","source-separate":",","source-meta":"","limit-type":"none","limit-num":"10","source-icon":"","source-text":"","enable-hover":"false","font-size":"13","line-height":"20","color":"#ffffff","0":"Default","font-family":"","font-weight":"300","text-decoration":"none","font-style":"false","text-transform":"uppercase","position":"relative","align":"t_l","absolute-unit":"px","top-bottom":"0","left-right":"0","display":"block","text-align":"center","float":"none","clear":"both","margin":["0","0","0","0"],"padding":["0","0","0","0"],"background-color":"#ffffff","bg-alpha":"0","shadow-color":"#000000","shadow-alpha":"100","box-shadow":["0","0","0","0"],"border":["0","0","0","0"],"border-radius":["0","0","0","0"],"border-radius-unit":"px","border-color":"transparent","border-style":"none","font-size-hover":"13","line-height-hover":"14","color-hover":"#ffffff","font-family-hover":"","font-weight-hover":"300","text-decoration-hover":"none","font-style-hover":"false","text-transform-hover":"none","background-color-hover":"#ffffff","bg-alpha-hover":"15","shadow-color-hover":"#000000","shadow-alpha-hover":"100","box-shadow-hover":["0","0","0","0"],"border-hover":["0","0","0","0"],"border-radius-hover":["0","0","0","0"],"border-radius-unit-hover":"px","border-color-hover":"transparent","border-style-hover":"none","hideunder":"0","hide-on-video":"false","show-on-sale":"false","show-if-featured":"false","transition":"flipdown","transition-type":"","delay":"57","link-type":"none","url-link":"","meta-link":"","javascript-link":"","tag-type":"div","force-important":"true","attribute":"","class":"","rel":""}', true)
		),
'tmp-white-on-dark-13px' => array(
		'id' => '-1',
		'name' => 'White on Dark 13px',
		'default' => 'true',
		'settings' => json_decode('{"source":"woocommerce","source-post":"title","source-woocommerce":"wc_add_to_cart_button","source-separate":",","source-meta":"","limit-type":"none","limit-num":"10","source-icon":"","source-text":"","enable-hover":"true","font-size":"13","line-height":"20","color":"#ffffff","0":"Default","font-family":"\"Raleway\"","font-weight":"800","text-decoration":"none","font-style":"false","text-transform":"uppercase","position":"relative","align":"t_l","absolute-unit":"px","top-bottom":"0","left-right":"0","display":"inline-block","text-align":"center","float":"none","clear":"both","margin":["0","0","0","0"],"padding":["5","10","4","10"],"background-color":"#000000","bg-alpha":"15","shadow-color":"#000000","shadow-alpha":"100","box-shadow":["0","0","0","0"],"border":["0","0","0","0"],"border-radius":["0","0","0","0"],"border-radius-unit":"px","border-color":"transparent","border-style":"none","font-size-hover":"13","line-height-hover":"20","color-hover":"#ffffff","font-family-hover":"\"Raleway\"","font-weight-hover":"800","text-decoration-hover":"none","font-style-hover":"false","text-transform-hover":"uppercase","background-color-hover":"#ffffff","bg-alpha-hover":"15","shadow-color-hover":"#000000","shadow-alpha-hover":"100","box-shadow-hover":["0","0","0","0"],"border-hover":["0","0","0","0"],"border-radius-hover":["0","0","0","0"],"border-radius-unit-hover":"px","border-color-hover":"transparent","border-style-hover":"none","hideunder":"0","hide-on-video":"false","show-on-sale":"false","show-if-featured":"false","transition":"flipup","transition-type":"","delay":"10","link-type":"none","url-link":"","meta-link":"","javascript-link":"","tag-type":"div","force-important":"true","attribute":"","class":"","rel":""}', true)
		),
'tmp-price-white-on-red-17px' => array(
		'id' => '-1',
		'name' => 'Price White on Red 17px',
		'default' => 'true',
		'settings' => json_decode('{"source":"woocommerce","source-post":"title","source-woocommerce":"wc_full_price","source-separate":",","source-meta":"","limit-type":"none","limit-num":"10","source-icon":"","source-text":"","enable-hover":"false","font-size":"17","line-height":"22","color":"#ffffff","0":"Default","font-family":"\"Open Sans\"","font-weight":"700","text-decoration":"none","font-style":"false","text-transform":"capitalize","position":"relative","align":"t_l","absolute-unit":"px","top-bottom":"0","left-right":"0","display":"inline-block","text-align":"center","float":"none","clear":"none","margin":["10","0","0","0"],"padding":["2","7","1","7"],"background-color":"#e33a0c","bg-alpha":"100","shadow-color":"#000000","shadow-alpha":"100","box-shadow":["0","0","0","0"],"border":["0","0","0","0"],"border-radius":["0","0","0","0"],"border-radius-unit":"px","border-color":"transparent","border-style":"none","font-size-hover":"13","line-height-hover":"14","color-hover":"#ffffff","font-family-hover":"","font-weight-hover":"700","text-decoration-hover":"none","font-style-hover":"false","text-transform-hover":"uppercase","background-color-hover":"#ffffff","bg-alpha-hover":"15","shadow-color-hover":"#000000","shadow-alpha-hover":"100","box-shadow-hover":["0","0","0","0"],"border-hover":["0","0","0","0"],"border-radius-hover":["0","0","0","0"],"border-radius-unit-hover":"px","border-color-hover":"transparent","border-style-hover":"none","hideunder":"0","hide-on-video":"false","show-on-sale":"false","show-if-featured":"false","transition":"slideleft","transition-type":"","delay":"30","link-type":"none","url-link":"","meta-link":"","javascript-link":"","tag-type":"div","force-important":"false","attribute":"","class":"","rel":""}', true)
		),
'tmp-black-17px' => array(
		'id' => '-1',
		'name' => 'Black 17px',
		'default' => 'true',
		'settings' => json_decode('{"source":"post","source-post":"title","source-woocommerce":"wc_full_price","source-separate":",","source-meta":"","limit-type":"none","limit-num":"20","source-icon":"","source-text":"","enable-hover":"false","font-size":"17","line-height":"22","color":"#000000","0":"Default","font-family":"\"Raleway\"","font-weight":"700","text-decoration":"none","font-style":"false","text-transform":"capitalize","position":"relative","align":"t_l","absolute-unit":"px","top-bottom":"0","left-right":"0","display":"block","text-align":"center","float":"none","clear":"none","margin":["0","0","0","0"],"padding":["0","0","0","0"],"background-color":"#ffffff","bg-alpha":"0","shadow-color":"#000000","shadow-alpha":"100","box-shadow":["0","0","0","0"],"border":["0","0","0","0"],"border-radius":["0","0","0","0"],"border-radius-unit":"px","border-color":"transparent","border-style":"none","font-size-hover":"13","line-height-hover":"14","color-hover":"#ffffff","font-family-hover":"","font-weight-hover":"700","text-decoration-hover":"none","font-style-hover":"false","text-transform-hover":"uppercase","background-color-hover":"#ffffff","bg-alpha-hover":"15","shadow-color-hover":"#000000","shadow-alpha-hover":"100","box-shadow-hover":["0","0","0","0"],"border-hover":["0","0","0","0"],"border-radius-hover":["0","0","0","0"],"border-radius-unit-hover":"px","border-color-hover":"transparent","border-style-hover":"none","hideunder":"0","hide-on-video":"false","show-on-sale":"false","show-if-featured":"false","transition":"none","transition-type":"","delay":"30","link-type":"post","url-link":"","meta-link":"","javascript-link":"","tag-type":"div","force-important":"true","attribute":"","class":"","rel":""}', true)
		),
'tmp-black-capital-13px' => array(
		'id' => '-1',
		'name' => 'Black Capital 13px',
		'default' => 'true',
		'settings' => json_decode('{"source":"woocommerce","source-post":"title","source-woocommerce":"wc_star_rating","source-separate":",","source-meta":"","limit-type":"none","limit-num":"10","source-icon":"","source-text":"","enable-hover":"false","font-size":"13","line-height":"20","color":"#000000","0":"Default","font-family":"","font-weight":"700","text-decoration":"none","font-style":"false","text-transform":"uppercase","position":"relative","align":"t_l","absolute-unit":"px","top-bottom":"0","left-right":"0","display":"inline-block","text-align":"center","float":"none","clear":"both","margin":["0","0","0","0"],"padding":["5","10","5","10"],"background-color":"#ffffff","bg-alpha":"0","shadow-color":"#000000","shadow-alpha":"100","box-shadow":["0","0","0","0"],"border":["0","0","0","0"],"border-radius":["0","0","0","0"],"border-radius-unit":"px","border-color":"transparent","border-style":"none","font-size-hover":"13","line-height-hover":"14","color-hover":"#ffffff","font-family-hover":"","font-weight-hover":"700","text-decoration-hover":"none","font-style-hover":"false","text-transform-hover":"uppercase","background-color-hover":"#ffffff","bg-alpha-hover":"15","shadow-color-hover":"#000000","shadow-alpha-hover":"100","box-shadow-hover":["0","0","0","0"],"border-hover":["0","0","0","0"],"border-radius-hover":["0","0","0","0"],"border-radius-unit-hover":"px","border-color-hover":"transparent","border-style-hover":"none","hideunder":"0","hide-on-video":"false","show-on-sale":"false","show-if-featured":"false","transition":"slideleft","transition-type":"","delay":"30","link-type":"none","url-link":"","meta-link":"","javascript-link":"","tag-type":"div","force-important":"true","attribute":"","class":"","rel":""}', true)
		),
'tmp-white-thin-20px' => array(
		'id' => '-1',
		'name' => 'White Thin 20px',
		'default' => 'true',
		'settings' => json_decode('{"source":"post","source-post":"title","source-woocommerce":"wc_full_price","source-separate":",","source-meta":"","limit-type":"none","limit-num":"10","source-icon":"","source-text":"","enable-hover":"false","font-size":"20","line-height":"25","color":"#ffffff","0":"Default","font-family":"","font-weight":"500","text-decoration":"none","font-style":"false","text-transform":"capitalize","position":"relative","align":"t_l","absolute-unit":"px","top-bottom":"0","left-right":"0","display":"block","text-align":"left","float":"none","clear":"both","margin":["0","0","20","0"],"padding":["0","0","0","0"],"background-color":"#ffffff","bg-alpha":"0","shadow-color":"#000000","shadow-alpha":"100","box-shadow":["0","0","0","0"],"border":["0","0","0","0"],"border-radius":["0","0","0","0"],"border-radius-unit":"px","border-color":"transparent","border-style":"none","font-size-hover":"13","line-height-hover":"14","color-hover":"#ffffff","font-family-hover":"","font-weight-hover":"700","text-decoration-hover":"none","font-style-hover":"false","text-transform-hover":"uppercase","background-color-hover":"#ffffff","bg-alpha-hover":"15","shadow-color-hover":"#000000","shadow-alpha-hover":"100","box-shadow-hover":["0","0","0","0"],"border-hover":["0","0","0","0"],"border-radius-hover":["0","0","0","0"],"border-radius-unit-hover":"px","border-color-hover":"transparent","border-style-hover":"none","hideunder":"0","hide-on-video":"false","show-on-sale":"false","show-if-featured":"false","transition":"none","transition-type":"","delay":"30","link-type":"none","url-link":"","meta-link":"","javascript-link":"","tag-type":"div","force-important":"true","attribute":"","class":"","rel":""}', true)
		),
'tmp-white-12px-with-separator' => array(
		'id' => '-1',
		'name' => 'White 12px with Separator',
		'default' => 'true',
		'settings' => json_decode('{"source":"post","source-post":"date","source-woocommerce":"wc_full_price","source-separate":",","source-meta":"","limit-type":"none","limit-num":"10","source-icon":"","source-text":"","enable-hover":"false","font-size":"12","line-height":"14","color":"#aaaaaa","0":"Default","font-family":"","font-weight":"300","text-decoration":"none","font-style":"false","text-transform":"capitalize","position":"relative","align":"t_l","absolute-unit":"px","top-bottom":"0","left-right":"0","display":"inline-block","text-align":"center","float":"left","clear":"none","margin":["0","0","0","0"],"padding":["0","10","0","0"],"background-color":"#ffffff","bg-alpha":"0","shadow-color":"#000000","shadow-alpha":"100","box-shadow":["0","0","0","0"],"border":["0","1","0","0"],"border-radius":["0","0","0","0"],"border-radius-unit":"px","border-color":"#aaaaaa","border-style":"solid","font-size-hover":"13","line-height-hover":"14","color-hover":"#ffffff","font-family-hover":"","font-weight-hover":"300","text-decoration-hover":"none","font-style-hover":"false","text-transform-hover":"none","background-color-hover":"#ffffff","bg-alpha-hover":"15","shadow-color-hover":"#000000","shadow-alpha-hover":"100","box-shadow-hover":["0","0","0","0"],"border-hover":["0","0","0","0"],"border-radius-hover":["0","0","0","0"],"border-radius-unit-hover":"px","border-color-hover":"transparent","border-style-hover":"none","hideunder":"0","hide-on-video":"false","show-on-sale":"false","show-if-featured":"false","transition":"none","transition-type":"","delay":"34","link-type":"none","url-link":"","meta-link":"","javascript-link":"","tag-type":"div","force-important":"true","attribute":"","class":"","rel":""}', true)
		),
'tmp-white-thin-12px' => array(
		'id' => '-1',
		'name' => 'White Thin 12px',
		'default' => 'true',
		'settings' => json_decode('{"source":"post","source-post":"cat_list","source-woocommerce":"wc_full_price","source-separate":",","source-meta":"","limit-type":"none","limit-num":"10","source-icon":"","source-text":"","enable-hover":"false","font-size":"12","line-height":"14","color":"#aaaaaa","0":"Default","font-family":"","font-weight":"300","text-decoration":"none","font-style":"false","text-transform":"capitalize","position":"relative","align":"t_l","absolute-unit":"px","top-bottom":"0","left-right":"0","display":"inline-block","text-align":"center","float":"left","clear":"none","margin":["0","0","0","10"],"padding":["0","10","0","0"],"background-color":"#ffffff","bg-alpha":"0","shadow-color":"#000000","shadow-alpha":"100","box-shadow":["0","0","0","0"],"border":["0","0","0","0"],"border-radius":["0","0","0","0"],"border-radius-unit":"px","border-color":"#aaaaaa","border-style":"solid","font-size-hover":"13","line-height-hover":"14","color-hover":"#ffffff","font-family-hover":"","font-weight-hover":"300","text-decoration-hover":"none","font-style-hover":"false","text-transform-hover":"none","background-color-hover":"#ffffff","bg-alpha-hover":"15","shadow-color-hover":"#000000","shadow-alpha-hover":"100","box-shadow-hover":["0","0","0","0"],"border-hover":["0","0","0","0"],"border-radius-hover":["0","0","0","0"],"border-radius-unit-hover":"px","border-color-hover":"transparent","border-style-hover":"none","hideunder":"0","hide-on-video":"false","show-on-sale":"false","show-if-featured":"false","transition":"none","transition-type":"","delay":"34","link-type":"none","url-link":"","meta-link":"","javascript-link":"","tag-type":"div","force-important":"true","attribute":"","class":"","rel":""}', true)
		),
'tmp-white-bold-20px' => array(
		'id' => '-1',
		'name' => 'White Bold 20px',
		'default' => 'true',
		'settings' => json_decode('{"source":"post","source-post":"title","source-woocommerce":"wc_full_price","source-separate":",","source-meta":"","limit-type":"none","limit-num":"10","source-icon":"","source-text":"","enable-hover":"false","font-size":"20","line-height":"25","color":"#ffffff","0":"Default","font-family":"\"Raleway\"","font-weight":"700","text-decoration":"none","font-style":"false","text-transform":"capitalize","position":"relative","align":"t_l","absolute-unit":"px","top-bottom":"0","left-right":"0","display":"block","text-align":"left","float":"none","clear":"both","margin":["0","0","20","0"],"padding":["0","0","0","0"],"background-color":"#ffffff","bg-alpha":"0","shadow-color":"#000000","shadow-alpha":"100","box-shadow":["0","0","0","0"],"border":["0","0","0","0"],"border-radius":["0","0","0","0"],"border-radius-unit":"px","border-color":"transparent","border-style":"none","font-size-hover":"20","line-height-hover":"25","color-hover":"#ffffff","font-family-hover":"\"Raleway\"","font-weight-hover":"700","text-decoration-hover":"none","font-style-hover":"false","text-transform-hover":"capitalize","background-color-hover":"#ffffff","bg-alpha-hover":"0","shadow-color-hover":"#000000","shadow-alpha-hover":"100","box-shadow-hover":["0","0","0","0"],"border-hover":["0","0","0","0"],"border-radius-hover":["0","0","0","0"],"border-radius-unit-hover":"px","border-color-hover":"transparent","border-style-hover":"none","hideunder":"0","hide-on-video":"false","show-on-sale":"false","show-if-featured":"false","transition":"none","transition-type":"","delay":"30","link-type":"none","url-link":"","meta-link":"","javascript-link":"","tag-type":"div","force-important":"false","attribute":"","class":"","rel":""}', true)
		),
'tmp-white-on-dark-capital-12px' => array(
		'id' => '-1',
		'name' => 'White on Dark Capital 12px',
		'default' => 'true',
		'settings' => json_decode('{"source":"text","source-post":"title","source-woocommerce":"wc_full_price","source-separate":",","source-meta":"","limit-type":"none","limit-num":"10","source-icon":"","source-text":"READ MORE","enable-hover":"true","font-size":"12","line-height":"20","color":"#ffffff","0":"Default","font-family":"\"Raleway\"","font-weight":"800","text-decoration":"none","font-style":"false","text-transform":"uppercase","position":"relative","align":"t_l","absolute-unit":"px","top-bottom":"0","left-right":"0","display":"inline-block","text-align":"center","float":"none","clear":"both","margin":["0","0","0","0"],"padding":["5","10","5","10"],"background-color":"#000000","bg-alpha":"25","shadow-color":"#000000","shadow-alpha":"100","box-shadow":["0","0","0","0"],"border":["0","0","0","0"],"border-radius":["0","0","0","0"],"border-radius-unit":"px","border-color":"transparent","border-style":"none","font-size-hover":"12","line-height-hover":"20","color-hover":"#ffffff","font-family-hover":"\"Raleway\"","font-weight-hover":"800","text-decoration-hover":"none","font-style-hover":"false","text-transform-hover":"uppercase","background-color-hover":"#000000","bg-alpha-hover":"100","shadow-color-hover":"#000000","shadow-alpha-hover":"100","box-shadow-hover":["0","0","0","0"],"border-hover":["0","0","0","0"],"border-radius-hover":["0","0","0","0"],"border-radius-unit-hover":"px","border-color-hover":"transparent","border-style-hover":"none","hideunder":"0","hide-on-video":"false","show-on-sale":"false","show-if-featured":"false","transition":"flipup","transition-type":"","delay":"10","link-type":"post","url-link":"","meta-link":"","javascript-link":"","tag-type":"div","force-important":"false","attribute":"","class":"","rel":""}', true)
		),
'tmp-white-line' => array(
		'id' => '-1',
		'name' => 'White Line',
		'default' => 'true',
		'settings' => json_decode('{"source":"text","source-post":"title","source-woocommerce":"wc_full_price","source-separate":",","source-meta":"","limit-type":"none","limit-num":"10","source-icon":"","source-text":"anemptytextlline","enable-hover":"false","font-size":"6","line-height":"7","color":"transparent","0":"Default","font-family":"","font-weight":"300","text-decoration":"none","font-style":"false","text-transform":"uppercase","position":"relative","align":"t_l","absolute-unit":"px","top-bottom":"0","left-right":"0","display":"inline-block","text-align":"center","float":"none","clear":"both","margin":["0","0","0","0"],"padding":["0","0","0","0"],"background-color":"#ffffff","bg-alpha":"0","shadow-color":"#000000","shadow-alpha":"100","box-shadow":["0","0","0","0"],"border":["2","0","0","0"],"border-radius":["0","0","0","0"],"border-radius-unit":"px","border-color":"#ffffff","border-style":"solid","font-size-hover":"13","line-height-hover":"14","color-hover":"#ffffff","font-family-hover":"","font-weight-hover":"300","text-decoration-hover":"none","font-style-hover":"false","text-transform-hover":"none","background-color-hover":"#ffffff","bg-alpha-hover":"15","shadow-color-hover":"#000000","shadow-alpha-hover":"100","box-shadow-hover":["0","0","0","0"],"border-hover":["0","0","0","0"],"border-radius-hover":["0","0","0","0"],"border-radius-unit-hover":"px","border-color-hover":"transparent","border-style-hover":"none","hideunder":"0","hide-on-video":"false","show-on-sale":"false","show-if-featured":"false","transition":"zoomback","transition-type":"","delay":"25","link-type":"none","url-link":"","meta-link":"","javascript-link":"","tag-type":"div","force-important":"true","attribute":"","class":"","rel":""}', true)
		),
'tmp-white-on-black-50px' => array(
		'id' => '-1',
		'name' => 'White on Black 50px',
		'default' => 'true',
		'settings' => json_decode('{"source":"text","source-post":"title","source-woocommerce":"wc_full_price","source-separate":",","source-meta":"","limit-type":"none","limit-num":"10","source-icon":"","source-text":"<span style=\"font-size:30px; font-weight:300;\">$<\\/span> 24.99","enable-hover":"false","font-size":"50","line-height":"50","color":"#ffffff","0":"Default","font-family":"\"Raleway\"","font-weight":"800","text-decoration":"none","font-style":"false","text-transform":"uppercase","position":"relative","align":"t_l","absolute-unit":"px","top-bottom":"0","left-right":"0","display":"inline-block","text-align":"center","float":"none","clear":"both","margin":["80","0","-6","0"],"padding":["1","10","5","10"],"background-color":"#000000","bg-alpha":"100","shadow-color":"#000000","shadow-alpha":"100","box-shadow":["0","0","0","0"],"border":["0","0","0","0"],"border-radius":["0","0","0","0"],"border-radius-unit":"px","border-color":"transparent","border-style":"none","font-size-hover":"13","line-height-hover":"14","color-hover":"#ffffff","font-family-hover":"","font-weight-hover":"700","text-decoration-hover":"none","font-style-hover":"false","text-transform-hover":"uppercase","background-color-hover":"#ffffff","bg-alpha-hover":"15","shadow-color-hover":"#000000","shadow-alpha-hover":"100","box-shadow-hover":["0","0","0","0"],"border-hover":["0","0","0","0"],"border-radius-hover":["0","0","0","0"],"border-radius-unit-hover":"px","border-color-hover":"transparent","border-style-hover":"none","hideunder":"0","hide-on-video":"false","show-on-sale":"false","show-if-featured":"false","transition":"flipdown","transition-type":"out","delay":"0","link-type":"none","url-link":"","meta-link":"","javascript-link":"","tag-type":"div","force-important":"false","attribute":"","class":"","rel":""}', true)
		),
'tmp-black-50px' => array(
		'id' => '-1',
		'name' => 'Black 50px',
		'default' => 'true',
		'settings' => json_decode('{"source":"text","source-post":"title","source-woocommerce":"wc_full_price","source-separate":",","source-meta":"","limit-type":"none","limit-num":"10","source-icon":"","source-text":"<span style=\"font-size:30px; font-weight:300;\">$<\\/span> 39.99","enable-hover":"false","font-size":"50","line-height":"50","color":"#000000","0":"Default","font-family":"\"Raleway\"","font-weight":"800","text-decoration":"none","font-style":"false","text-transform":"uppercase","position":"relative","align":"t_l","absolute-unit":"px","top-bottom":"0","left-right":"0","display":"block","text-align":"center","float":"none","clear":"none","margin":["0","0","0","0"],"padding":["20","20","0","20"],"background-color":"#eeeeee","bg-alpha":"100","shadow-color":"#000000","shadow-alpha":"100","box-shadow":["0","0","0","0"],"border":["1","0","0","0"],"border-radius":["0","0","0","0"],"border-radius-unit":"px","border-color":"#e5e5e5","border-style":"solid","font-size-hover":"13","line-height-hover":"14","color-hover":"#ffffff","font-family-hover":"","font-weight-hover":"300","text-decoration-hover":"none","font-style-hover":"false","text-transform-hover":"none","background-color-hover":"#ffffff","bg-alpha-hover":"15","shadow-color-hover":"#000000","shadow-alpha-hover":"100","box-shadow-hover":["0","0","0","0"],"border-hover":["0","0","0","0"],"border-radius-hover":["0","0","0","0"],"border-radius-unit-hover":"px","border-color-hover":"transparent","border-style-hover":"none","hideunder":"0","hide-on-video":"false","show-on-sale":"false","show-if-featured":"false","transition":"slideright","transition-type":"","delay":"34","link-type":"none","url-link":"","meta-link":"","javascript-link":"","tag-type":"div","force-important":"false","attribute":"","class":"","rel":""}', true)
		),
'tmp-gray-15px' => array(
		'id' => '-1',
		'name' => 'Gray 15px',
		'default' => 'true',
		'settings' => json_decode('{"source":"text","source-post":"title","source-woocommerce":"wc_full_price","source-separate":",","source-meta":"","limit-type":"none","limit-num":"10","source-icon":"","source-text":"4GB Webspace Included","enable-hover":"false","font-size":"15","line-height":"18","color":"#777777","0":"Default","font-family":"\"Open Sans\"","font-weight":"400","text-decoration":"none","font-style":"false","text-transform":"capitalize","position":"relative","align":"t_l","absolute-unit":"px","top-bottom":"0","left-right":"0","display":"block","text-align":"center","float":"none","clear":"none","margin":["0","0","0","0"],"padding":["17","20","17","20"],"background-color":"#ffffff","bg-alpha":"0","shadow-color":"#000000","shadow-alpha":"100","box-shadow":["0","0","0","0"],"border":["1","0","0","0"],"border-radius":["0","0","0","0"],"border-radius-unit":"px","border-color":"#e5e5e5","border-style":"solid","font-size-hover":"13","line-height-hover":"14","color-hover":"#ffffff","font-family-hover":"","font-weight-hover":"300","text-decoration-hover":"none","font-style-hover":"false","text-transform-hover":"none","background-color-hover":"#ffffff","bg-alpha-hover":"15","shadow-color-hover":"#000000","shadow-alpha-hover":"100","box-shadow-hover":["0","0","0","0"],"border-hover":["0","0","0","0"],"border-radius-hover":["0","0","0","0"],"border-radius-unit-hover":"px","border-color-hover":"transparent","border-style-hover":"none","hideunder":"0","hide-on-video":"false","show-on-sale":"false","show-if-featured":"false","transition":"slideright","transition-type":"","delay":"34","link-type":"none","url-link":"","meta-link":"","javascript-link":"","tag-type":"div","force-important":"false","attribute":"","class":"","rel":""}', true)
		),
'tmp-white-on-bordo-13px' => array(
		'id' => '-1',
		'name' => 'White on Bordo 13px',
		'default' => 'true',
		'settings' => json_decode('{"source":"post","source-post":"date_modified","source-woocommerce":"wc_full_price","source-separate":"","source-meta":"","limit-type":"none","limit-num":"","source-icon":"","source-text":"","enable-hover":"false","font-size":"13","line-height":"20","color":"#ffffff","0":"Default","font-family":"","font-weight":"700","text-decoration":"none","font-style":"false","text-transform":"uppercase","position":"relative","align":"t_l","absolute-unit":"px","top-bottom":"0","left-right":"0","display":"inline-block","text-align":"center","float":"left","clear":"both","margin":["0","0","0","0"],"padding":["10","20","10","20"],"background-color":"#4d384b","bg-alpha":"100","shadow-color":"#000000","shadow-alpha":"100","box-shadow":["0","0","0","0"],"border":["0","0","0","0"],"border-radius":["0","0","0","0"],"border-radius-unit":"px","border-color":"transparent","border-style":"none","font-size-hover":"13","line-height-hover":"14","color-hover":"#ffffff","font-family-hover":"","font-weight-hover":"700","text-decoration-hover":"none","font-style-hover":"false","text-transform-hover":"uppercase","background-color-hover":"#ffffff","bg-alpha-hover":"15","shadow-color-hover":"#000000","shadow-alpha-hover":"100","box-shadow-hover":["0","0","0","0"],"border-hover":["0","0","0","0"],"border-radius-hover":["0","0","0","0"],"border-radius-unit-hover":"px","border-color-hover":"transparent","border-style-hover":"none","hideunder":"0","hide-on-video":"false","show-on-sale":"false","show-if-featured":"false","transition":"slideup","transition-type":"out","delay":"6","link-type":"none","url-link":"","meta-link":"","javascript-link":"","tag-type":"div","force-important":"false","attribute":"","class":"","rel":""}', true)
		),
'tmp-white-bold-capital-35px' => array(
		'id' => '-1',
		'name' => 'White Bold Capital 35px',
		'default' => 'true',
		'settings' => json_decode('{"source":"post","source-post":"title","source-woocommerce":"wc_full_price","source-separate":",","source-meta":"","limit-type":"none","limit-num":"3","source-icon":"","source-text":"","enable-hover":"false","font-size":"35","line-height":"38","color":"#ffffff","0":"Default","font-family":"\"Raleway\"","font-weight":"800","text-decoration":"none","font-style":"false","text-transform":"uppercase","position":"relative","align":"t_l","absolute-unit":"px","top-bottom":"0","left-right":"0","display":"block","text-align":"left","float":"none","clear":"both","margin":["20","0","0","20"],"padding":["0","20","0","0"],"background-color":"#ffffff","bg-alpha":"0","shadow-color":"#000000","shadow-alpha":"100","box-shadow":["0","0","0","0"],"border":["0","0","0","0"],"border-radius":["0","0","0","0"],"border-radius-unit":"px","border-color":"transparent","border-style":"none","font-size-hover":"13","line-height-hover":"14","color-hover":"#ffffff","font-family-hover":"","font-weight-hover":"700","text-decoration-hover":"none","font-style-hover":"false","text-transform-hover":"uppercase","background-color-hover":"#ffffff","bg-alpha-hover":"15","shadow-color-hover":"#000000","shadow-alpha-hover":"100","box-shadow-hover":["0","0","0","0"],"border-hover":["0","0","0","0"],"border-radius-hover":["0","0","0","0"],"border-radius-unit-hover":"px","border-color-hover":"transparent","border-style-hover":"none","hideunder":"0","hide-on-video":"false","show-on-sale":"false","show-if-featured":"false","transition":"none","transition-type":"","delay":"30","link-type":"post","url-link":"","meta-link":"","javascript-link":"","tag-type":"div","force-important":"true","attribute":"","class":"","rel":""}', true)
		),
'tmp-white-thin-18px' => array(
		'id' => '-1',
		'name' => 'White Thin 18px',
		'default' => 'true',
		'settings' => json_decode('{"source":"post","source-post":"excerpt","source-woocommerce":"wc_full_price","source-separate":",","source-meta":"","limit-type":"words","limit-num":"8","source-icon":"","source-text":"","enable-hover":"false","font-size":"18","line-height":"22","color":"#ffffff","0":"Default","font-family":"\"Raleway\"","font-weight":"400","text-decoration":"none","font-style":"false","text-transform":"uppercase","position":"relative","align":"t_l","absolute-unit":"px","top-bottom":"0","left-right":"0","display":"block","text-align":"left","float":"none","clear":"both","margin":["5","0","20","20"],"padding":["0","20","0","0"],"background-color":"#ffffff","bg-alpha":"0","shadow-color":"#000000","shadow-alpha":"100","box-shadow":["0","0","0","0"],"border":["0","0","0","0"],"border-radius":["0","0","0","0"],"border-radius-unit":"px","border-color":"transparent","border-style":"none","font-size-hover":"13","line-height-hover":"14","color-hover":"#ffffff","font-family-hover":"","font-weight-hover":"700","text-decoration-hover":"none","font-style-hover":"false","text-transform-hover":"uppercase","background-color-hover":"#ffffff","bg-alpha-hover":"15","shadow-color-hover":"#000000","shadow-alpha-hover":"100","box-shadow-hover":["0","0","0","0"],"border-hover":["0","0","0","0"],"border-radius-hover":["0","0","0","0"],"border-radius-unit-hover":"px","border-color-hover":"transparent","border-style-hover":"none","hideunder":"0","hide-on-video":"false","show-on-sale":"false","show-if-featured":"false","transition":"none","transition-type":"","delay":"30","link-type":"none","url-link":"","meta-link":"","javascript-link":"","tag-type":"div","force-important":"false","attribute":"","class":"","rel":""}', true)
		),
'tmp-red-button-rounded-12px' => array(
		'id' => '-1',
		'name' => 'Red Button Rounded 12px',
		'default' => 'true',
		'settings' => json_decode('{"source":"woocommerce","source-post":"title","source-woocommerce":"wc_add_to_cart_button","source-separate":",","source-meta":"","limit-type":"none","limit-num":"10","source-icon":"","source-text":"","enable-hover":"true","font-size":"12","line-height":"20","color":"#ffffff","0":"Default","font-family":"\"Open Sans\"","font-weight":"700","text-decoration":"none","font-style":"false","text-transform":"capitalize","position":"relative","align":"t_l","absolute-unit":"px","top-bottom":"0","left-right":"0","display":"inline-block","text-align":"center","float":"none","clear":"both","margin":["0","0","0","0"],"padding":["5","10","4","10"],"background-color":"#e33a0c","bg-alpha":"100","shadow-color":"#000000","shadow-alpha":"100","box-shadow":["0","0","0","0"],"border":["0","0","0","0"],"border-radius":["5","5","5","5"],"border-radius-unit":"px","border-color":"#e5e5e5","border-style":"none","font-size-hover":"12","line-height-hover":"20","color-hover":"#ffffff","font-family-hover":"\"Open Sans\"","font-weight-hover":"700","text-decoration-hover":"none","font-style-hover":"false","text-transform-hover":"capitalize","background-color-hover":"#000000","bg-alpha-hover":"100","shadow-color-hover":"#000000","shadow-alpha-hover":"100","box-shadow-hover":["0","0","0","0"],"border-hover":["0","0","0","0"],"border-radius-hover":["5","5","5","5"],"border-radius-unit-hover":"px","border-color-hover":"#e33a0c","border-style-hover":"none","hideunder":"0","hide-on-video":"false","show-on-sale":"false","show-if-featured":"false","transition":"flipup","transition-type":"","delay":"10","link-type":"none","url-link":"","meta-link":"","javascript-link":"","tag-type":"div","force-important":"true","attribute":"","class":"","rel":""}', true)
		),
'tmp-green-16px' => array(
		'id' => '-1',
		'name' => 'Green 16px',
		'default' => 'true',
		'settings' => json_decode('{"source":"woocommerce","source-post":"title","source-woocommerce":"wc_full_price","source-separate":",","source-meta":"","limit-type":"none","limit-num":"10","source-icon":"","source-text":"","enable-hover":"false","font-size":"16","line-height":"22","color":"#89af72","0":"Default","font-family":"\"Open Sans\"","font-weight":"700","text-decoration":"none","font-style":"false","text-transform":"none","position":"relative","align":"t_l","absolute-unit":"px","top-bottom":"0","left-right":"0","display":"inline-block","text-align":"center","float":"none","clear":"none","margin":["10","0","0","0"],"padding":["2","7","1","7"],"background-color":"#ffffff","bg-alpha":"0","shadow-color":"#000000","shadow-alpha":"100","box-shadow":["0","0","0","0"],"border":["0","0","0","0"],"border-radius":["0","0","0","0"],"border-radius-unit":"px","border-color":"transparent","border-style":"none","font-size-hover":"13","line-height-hover":"14","color-hover":"#ffffff","font-family-hover":"","font-weight-hover":"700","text-decoration-hover":"none","font-style-hover":"false","text-transform-hover":"uppercase","background-color-hover":"#ffffff","bg-alpha-hover":"15","shadow-color-hover":"#000000","shadow-alpha-hover":"100","box-shadow-hover":["0","0","0","0"],"border-hover":["0","0","0","0"],"border-radius-hover":["0","0","0","0"],"border-radius-unit-hover":"px","border-color-hover":"transparent","border-style-hover":"none","hideunder":"0","hide-on-video":"false","show-on-sale":"false","show-if-featured":"false","transition":"slideleft","transition-type":"","delay":"30","link-type":"none","url-link":"","meta-link":"","javascript-link":"","tag-type":"div","force-important":"false","attribute":"","class":"","rel":""}', true)
		)
);
?>