<!--components/molecules/card.php-->
<!-- This markup is generated by the CardComponent class, please do not write by hand -->
<?php
//This is how to use the card component

//Init component
$card = new \WonderWp\Theme\Components\CardComponent();
$card
	->setImage('http://placehold.it/300x150')
	->setTitle('Card title')
	->setContent('<p>Some quick example text to build on the card title and make up the bulk of the card\'s content.</p>
				  <a href="#" class="btn btn-primary">Go somewhere</a>')
	;

echo $card->getMarkup();
?>