<!--components/molecules/social-networks.php-->
<!-- This markup is generated by the ReseauxSociauxComponent class, please do not write by hand -->
<?php
//This is how to use the card component

//Init component
$rs = new \WonderWp\Theme\Components\ReseauxSociauxComponent();
echo $rs->getMarkup();
?>