<!-- components/molecules/social_networks.php -->
<!-- This markup is generated by the ReseauxSociauxComponent class, please do not write by hand -->

<!--This is how to use the card component

Init component
$rs = new \WonderWp\Theme\Child\Components\ReseauxSociaux\ReseauxSociauxComponent();
echo $rs->getMarkup();-->

<!--Static example-->
<ul class="social-networks">
    <li class="facebook"><a href="/" target="_blank">rs.follow.facebook</a></li>
    <li class="twitter"><a href="/" target="_blank">rs.follow.twitter</a></li>
    <li class="youtube"><a href="/" target="_blank">rs.follow.youtube</a></li>
    <li class="instagram"><a href="/" target="_blank">rs.follow.instagram</a></li>
    <li class="pinterest"><a href="/" target="_blank">rs.follow.pinterest</a></li>
    <li class="flickr"><a href="/" target="_blank">rs.follow.flickr</a></li>
</ul>