<!-- components/molecules/social_networks.php -->
<!-- This markup is generated by the ReseauxSociauxComponent class, please do not write by hand -->
<?php
//This is how to use the card component

//Init component
$rs = new \WonderWp\Theme\Child\Components\ReseauxSociaux\ReseauxSociauxComponent();
echo $rs->getMarkup();