<?php
/**
 * Do not edit this file. Edit the config files found in the config/ dir instead.
 * Test-specific configuration is found in config/environments/testing.php.
 */
require_once(dirname(__DIR__) . '/vendor/autoload.php');
require_once(dirname(__DIR__) . '/config/application.php');
