<?php
/**
 * Created by PhpStorm.
 * User: jeremydesvaux
 * Date: 02/09/2016
 * Time: 10:08
 */

namespace WonderWp\Plugin\Faq;

use Doctrine\ORM\EntityRepository;
use WonderWp\APlugin\AbstractPluginFrontendController;

class FaqPublicController extends AbstractPluginFrontendController{

    public function handleShortcode($atts)
    {
        if(empty($atts['locale'])){
            $atts['locale'] = get_locale();
        }
        if(empty($atts['vue'])){
            $atts['vue'] = 'accordion';
        }
        return parent::handleShortcode($atts);
    }

    public function defaultAction($atts)
    {
        return $this->listAction($atts); // TODO: Change the autogenerated stub
    }

    public function listAction($atts){

        /** @var EntityRepository $repository */
        $repository = $this->_entityManager->getRepository(FaqEntity::class);
        $filters = array('lang'=>$atts['locale']);
        $questions = $repository->findBy($filters);

        $viewContent = $this->renderView($atts['vue'],['questions'=>$questions]);
        return $viewContent;
    }

}