<?php
$array = array(
	'base' => 'ult_dualbutton', // shortcode base
	'presets' => array( // presets array
		//1
		array(
			'title' => 'Dual Button Style 1', // Title of preset
			'default' => false, // set true if if want to load this preset on newly created element
			'settings' => array(
				'btn_border_style' => 'solid',
				'btn_color_border' => '#7f7f7f',
				'btn_border_size' => '1',
				'button1_text' => 'See Now',
				'icon_link' => 'url:%23||',
				'btn1_background_color' => '#ffffff',
				'btn1_bghovercolor' => '#26b161',
				'icon' => 'Defaults-eye',
				'icon_size' => '25',
				'icon_color' => '#7f7f7f',
				'icon_hover_color' => '#ffffff',
				'button2_text' => 'Buy Now',
				'btn_icon_link' => 'url:%23||',
				'btn2_background_color' => '#ffffff',
				'btn2_bghovercolor' => '#26b161',
				'btn_icon' => 'Defaults-shopping-cart',
				'btn_icon_size' => '25',
				'btn_icon_color' => '#7f7f7f',
				'btn_iconhover_color' => '#ffffff',
				'divider_text' => 'or',
				'divider_text_color' => '#7f7f7f',
				'divider_bg_color' => '#ffffff',
				'divider_border_style' => 'solid',
				'divider_color_border' => '#7f7f7f',
				'divider_border_size' => '1',
				'btn1_text_color' => '#7f7f7f',
				'btn1_text_hovercolor' => '#ffffff',
				'btn2_text_color' => '#7f7f7f',
				'btn2_text_hovercolor' => '#ffffff',
				'title_font_size' => 'desktop:18px;',
				'title_line_ht' => 'desktop:18px;',
				'divider_border_radius' => '100',
			)
		),
		//2
		array(
			'title' => 'Dual Button Style 2', // Title of preset
			'default' => false, // set true if if want to load this preset on newly created element
			'settings' => array(
				'btn_hover_style' => 'Style 2',
				'btn_border_style' => 'solid',
				'btn_color_border' => '#7f7f7f',
				'btn_border_size' => '1',
				'button1_text' => 'See Now',
				'icon_link' => 'url:%23||',
				'btn1_background_color' => '#ffffff',
				'btn1_bghovercolor' => '#26b161',
				'icon' => 'Defaults-eye',
				'icon_size' => '25',
				'icon_color' => '#7f7f7f',
				'icon_hover_color' => '#ffffff',
				'button2_text' => 'Buy Now',
				'btn_icon_link' => 'url:%23||',
				'btn2_background_color' => '#ffffff',
				'btn2_bghovercolor' => '#26b161',
				'btn_icon' => 'Defaults-shopping-cart',
				'btn_icon_size' => '25',
				'btn_icon_color' => '#7f7f7f',
				'btn_iconhover_color' => '#ffffff',
				'divider_text' => 'or',
				'divider_text_color' => '#7f7f7f',
				'divider_bg_color' => '#ffffff',
				'divider_border_style' => 'solid',
				'divider_color_border' => '#7f7f7f',
				'divider_border_size' => '1',
				'btn1_text_color' => '#7f7f7f',
				'btn1_text_hovercolor' => '#ffffff',
				'btn2_text_color' => '#7f7f7f',
				'btn2_text_hovercolor' => '#ffffff',
				'title_font_size' => 'desktop:18px;',
				'title_line_ht' => 'desktop:18px;',
				'divider_border_radius' => '100',
			)
		),
		//3
		array(
			'title' => 'Style 1 With Background', // Title of preset
			'default' => false, // set true if if want to load this preset on newly created element
			'settings' => array(
				'btn_border_style' => 'solid',
				'btn_color_border' => '#3f3f3f',
				'btn_border_size' => '1',
				'button1_text' => 'See Now',
				'icon_link' => 'url:%23||',
				'btn1_background_color' => '#26b161',
				'btn1_bghovercolor' => '#ffffff',
				'icon' => 'Defaults-eye',
				'icon_size' => '25',
				'icon_color' => '#ffffff',
				'icon_hover_color' => '#3f3f3f',
				'button2_text' => 'Buy Now',
				'btn_icon_link' => 'url:%23||',
				'btn2_background_color' => '#3f3f3f',
				'btn2_bghovercolor' => '#ffffff',
				'btn_icon' => 'Defaults-shopping-cart',
				'btn_icon_size' => '25',
				'btn_icon_color' => '#ffffff',
				'btn_iconhover_color' => '#3f3f3f',
				'divider_text' => 'or',
				'divider_text_color' => '#7f7f7f',
				'divider_bg_color' => '#ffffff',
				'divider_border_style' => 'solid',
				'divider_color_border' => '#7f7f7f',
				'divider_border_size' => '1',
				'btn1_text_color' => '#ffffff',
				'btn1_text_hovercolor' => '#3f3f3f',
				'btn2_text_color' => '#ffffff',
				'btn2_text_hovercolor' => '#3f3f3f',
				'title_font_size' => 'desktop:18px;',
				'title_line_ht' => 'desktop:18px;',
				'divider_border_radius' => '100',
				'btn_border_radius' => '10',
			)
		),
		//4
		array(
			'title' => ' Style 2 With Background', // Title of preset
			'default' => false, // set true if if want to load this preset on newly created element
			'settings' => array(
				'btn_hover_style' => 'Style 2',
				'btn_border_style' => 'solid',
				'btn_color_border' => '#3f3f3f',
				'btn_border_size' => '1',
				'button1_text' => 'See Now',
				'icon_link' => 'url:%23||',
				'btn1_background_color' => '#26b161',
				'btn1_bghovercolor' => '#ffffff',
				'icon' => 'Defaults-eye',
				'icon_size' => '25',
				'icon_color' => '#ffffff',
				'icon_hover_color' => '#3f3f3f',
				'button2_text' => 'Buy Now',
				'btn_icon_link' => 'url:%23||',
				'btn2_background_color' => '#3f3f3f',
				'btn2_bghovercolor' => '#ffffff',
				'btn_icon' => 'Defaults-shopping-cart',
				'btn_icon_size' => '25',
				'btn_icon_color' => '#ffffff',
				'btn_iconhover_color' => '#3f3f3f',
				'divider_text' => 'or',
				'divider_text_color' => '#7f7f7f',
				'divider_bg_color' => '#ffffff',
				'divider_border_style' => 'solid',
				'divider_color_border' => '#7f7f7f',
				'divider_border_size' => '1',
				'btn1_text_color' => '#ffffff',
				'btn1_text_hovercolor' => '#3f3f3f',
				'btn2_text_color' => '#ffffff',
				'btn2_text_hovercolor' => '#3f3f3f',
				'title_font_size' => 'desktop:18px;',
				'title_line_ht' => 'desktop:18px;',
				'divider_border_radius' => '100',
				'btn_border_radius' => '10',
			)
		),
		//5
		array(
			'title' => 'Style 1 With Custom Width', // Title of preset
			'default' => false, // set true if if want to load this preset on newly created element
			'settings' => array(
			 	'btn_border_style' => 'solid',
				'btn_color_border' => '#3f3f3f',
				'btn_border_size' => '1',
				'button1_text' => 'See Now',
				'icon_link' => 'url:%23||',
				'btn1_background_color' => '#26b161',
				'btn1_bghovercolor' => '#ffffff',
				'icon' => 'Defaults-eye',
				'icon_size' => '25',
				'icon_color' => '#ffffff',
				'icon_hover_color' => '#3f3f3f',
				'button2_text' => 'Buy Now',
				'btn_icon_link' => 'url:%23||',
				'btn2_background_color' => '#3f3f3f',
				'btn2_bghovercolor' => '#ffffff',
				'btn_icon' => 'Defaults-shopping-cart',
				'btn_icon_size' => '25',
				'btn_icon_color' => '#ffffff',
				'btn_iconhover_color' => '#3f3f3f',
				'divider_text' => 'or',
				'divider_text_color' => '#7f7f7f',
				'divider_bg_color' => '#ffffff',
				'divider_border_style' => 'solid',
				'divider_color_border' => '#7f7f7f',
				'divider_border_size' => '1',
				'btn1_text_color' => '#ffffff',
				'btn1_text_hovercolor' => '#3f3f3f',
				'btn2_text_color' => '#ffffff',
				'btn2_text_hovercolor' => '#3f3f3f',
				'title_font_size' => 'desktop:18px;',
				'title_line_ht' => 'desktop:18px;',
				'divider_border_radius' => '100',
				'btn_border_radius' => '10',
				'btn_width' => '200',
			)
		),
		//6
		array(
			'title' => 'Style 2 With Custom Width', // Title of preset
			'default' => false, // set true if if want to load this preset on newly created element
			'settings' => array(
				'btn_hover_style' => 'Style 2',
				'btn_border_style' => 'solid',
				'btn_color_border' => '#3f3f3f',
				'btn_border_size' => '1',
				'button1_text' => 'See Now',
				'icon_link' => 'url:%23||',
				'btn1_background_color' => '#26b161',
				'btn1_bghovercolor' => '#ffffff',
				'icon' => 'Defaults-eye',
				'icon_size' => '25',
				'icon_color' => '#ffffff',
				'icon_hover_color' => '#3f3f3f',
				'button2_text' => 'Buy Now',
				'btn_icon_link' => 'url:%23||',
				'btn2_background_color' => '#3f3f3f',
				'btn2_bghovercolor' => '#ffffff',
				'btn_icon' => 'Defaults-shopping-cart',
				'btn_icon_size' => '25',
				'btn_icon_color' => '#ffffff',
				'btn_iconhover_color' => '#3f3f3f',
				'divider_text' => 'or',
				'divider_text_color' => '#7f7f7f',
				'divider_bg_color' => '#ffffff',
				'divider_border_style' => 'solid',
				'divider_color_border' => '#7f7f7f',
				'divider_border_size' => '1',
				'btn1_text_color' => '#ffffff',
				'btn1_text_hovercolor' => '#3f3f3f',
				'btn2_text_color' => '#ffffff',
				'btn2_text_hovercolor' => '#3f3f3f',
				'title_font_size' => 'desktop:18px;',
				'title_line_ht' => 'desktop:18px;',
				'divider_border_radius' => '100',
				'btn_border_radius' => '10',
				'btn_width' => '200',
			)
		),
		//7
		array(
			'title' => ' Style 1 With Icon Seperator', // Title of preset
			'default' => false, // set true if if want to load this preset on newly created element
			'settings' => array(
				'btn_border_style' => 'solid',
				'btn_color_border' => '#3f3f3f',
				'btn_border_size' => '1',
				'button1_text' => 'See Now',
				'icon_link' => 'url:%23||',
				'btn1_background_color' => '#26b161',
				'btn1_bghovercolor' => '#ffffff',
				'icon' => 'Defaults-eye',
				'icon_size' => '25',
				'icon_color' => '#ffffff',
				'icon_hover_color' => '#3f3f3f',
				'button2_text' => 'Buy Now',
				'btn_icon_link' => 'url:%23||',
				'btn2_background_color' => '#3f3f3f',
				'btn2_bghovercolor' => '#ffffff',
				'btn_icon' => 'Defaults-shopping-cart',
				'btn_icon_size' => '25',
				'btn_icon_color' => '#ffffff',
				'btn_iconhover_color' => '#3f3f3f',
				'divider_style' => 'icon',
				'divider_text_color' => '#3f3f3f',
				'divider_bg_color' => '#ffffff',
				'divider_icon' => 'Defaults-trophy',
				'divider_border_style' => 'solid',
				'divider_color_border' => '#7f7f7f',
				'divider_border_size' => '1',
				'btn1_text_color' => '#ffffff',
				'btn1_text_hovercolor' => '#3f3f3f',
				'btn2_text_color' => '#ffffff',
				'btn2_text_hovercolor' => '#3f3f3f',
				'title_font_size' => 'desktop:18px;',
				'title_line_ht' => 'desktop:18px;',
				'divider_border_radius' => '100',
				'btn_border_radius' => '10',
				'btn_width' => '200',
			)
		),
		//8
		array(
			'title' => 'Style 2 With Image Separator', // Title of preset
			'default' => false, // set true if if want to load this preset on newly created element
			'settings' => array(
				'btn_hover_style' => 'Style 2',
				'btn_border_style' => 'solid',
				'btn_color_border' => '#3f3f3f',
				'btn_border_size' => '1',
				'button1_text' => 'See Now',
				'icon_link' => 'url:%23||',
				'btn1_background_color' => '#26b161',
				'btn1_bghovercolor' => '#ffffff',
				'icon' => 'Defaults-eye',
				'icon_size' => '25',
				'icon_color' => '#ffffff',
				'icon_hover_color' => '#3f3f3f',
				'button2_text' => 'Buy Now',
				'btn_icon_link' => 'url:%23||',
				'btn2_background_color' => '#3f3f3f',
				'btn2_bghovercolor' => '#ffffff',
				'btn_icon' => 'Defaults-shopping-cart',
				'btn_icon_size' => '25',
				'btn_icon_color' => '#ffffff',
				'btn_iconhover_color' => '#3f3f3f',
				'divider_style' => 'image',
				'divider_bg_color' => '#ffffff',
				'divider_icon_img' => '4325|http://presets.sharkz.in/wp-content/uploads/2014/10/051.png',
				'divider_border_style' => 'solid',
				'divider_color_border' => '#7f7f7f',
				'divider_border_size' => '1',
				'btn1_text_color' => '#ffffff',
				'btn1_text_hovercolor' => '#3f3f3f',
				'btn2_text_color' => '#ffffff',
				'btn2_text_hovercolor' => '#3f3f3f',
				'title_font_size' => 'desktop:18px;',
				'title_line_ht' => 'desktop:18px;',
				'divider_border_radius' => '100',
				'btn_border_radius' => '10',
				'btn_width' => '200',
			)
		),
	)
);// end of preset