name: Setup Composer with Cache
description: Install PHP + Composer and prime cache
inputs:
  php-version:
    required: true
runs:
  using: composite
  steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        coverage: none
        tools: composer
    - name: Cache composer
      uses: actions/cache@v4
      with:
        path: |
          ~/.composer/cache
          vendor
        key: composer-${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          composer-${{ runner.os }}-
