<?php $icons = array();
$icons['Defaults']['glass'] = array("class"=>'glass',"tags"=>'glass',"unicode"=>'');
$icons['Defaults']['music'] = array("class"=>'music',"tags"=>'music',"unicode"=>'');
$icons['Defaults']['search'] = array("class"=>'search',"tags"=>'search',"unicode"=>'');
$icons['Defaults']['envelope-o'] = array("class"=>'envelope-o',"tags"=>'envelope-o',"unicode"=>'');
$icons['Defaults']['heart'] = array("class"=>'heart',"tags"=>'heart',"unicode"=>'');
$icons['Defaults']['star'] = array("class"=>'star',"tags"=>'star',"unicode"=>'');
$icons['Defaults']['star-o'] = array("class"=>'star-o',"tags"=>'star-o',"unicode"=>'');
$icons['Defaults']['user'] = array("class"=>'user',"tags"=>'user',"unicode"=>'');
$icons['Defaults']['film'] = array("class"=>'film',"tags"=>'film',"unicode"=>'');
$icons['Defaults']['th-large'] = array("class"=>'th-large',"tags"=>'th-large',"unicode"=>'');
$icons['Defaults']['th'] = array("class"=>'th',"tags"=>'th',"unicode"=>'');
$icons['Defaults']['th-list'] = array("class"=>'th-list',"tags"=>'th-list',"unicode"=>'');
$icons['Defaults']['check'] = array("class"=>'check',"tags"=>'check',"unicode"=>'');
$icons['Defaults']['close, remove, times'] = array("class"=>'close remove times',"tags"=>'close,remove,times',"unicode"=>'');
$icons['Defaults']['search-plus'] = array("class"=>'search-plus',"tags"=>'search-plus',"unicode"=>'');
$icons['Defaults']['search-minus'] = array("class"=>'search-minus',"tags"=>'search-minus',"unicode"=>'');
$icons['Defaults']['power-off'] = array("class"=>'power-off',"tags"=>'power-off',"unicode"=>'');
$icons['Defaults']['signal'] = array("class"=>'signal',"tags"=>'signal',"unicode"=>'');
$icons['Defaults']['cog, gear'] = array("class"=>'cog gear',"tags"=>'cog,gear',"unicode"=>'');
$icons['Defaults']['trash-o'] = array("class"=>'trash-o',"tags"=>'trash-o',"unicode"=>'');
$icons['Defaults']['home'] = array("class"=>'home',"tags"=>'home',"unicode"=>'');
$icons['Defaults']['file-o'] = array("class"=>'file-o',"tags"=>'file-o',"unicode"=>'');
$icons['Defaults']['clock-o'] = array("class"=>'clock-o',"tags"=>'clock-o',"unicode"=>'');
$icons['Defaults']['road'] = array("class"=>'road',"tags"=>'road',"unicode"=>'');
$icons['Defaults']['download'] = array("class"=>'download',"tags"=>'download',"unicode"=>'');
$icons['Defaults']['arrow-circle-o-down'] = array("class"=>'arrow-circle-o-down',"tags"=>'arrow-circle-o-down',"unicode"=>'');
$icons['Defaults']['arrow-circle-o-up'] = array("class"=>'arrow-circle-o-up',"tags"=>'arrow-circle-o-up',"unicode"=>'');
$icons['Defaults']['inbox'] = array("class"=>'inbox',"tags"=>'inbox',"unicode"=>'');
$icons['Defaults']['play-circle-o'] = array("class"=>'play-circle-o',"tags"=>'play-circle-o',"unicode"=>'');
$icons['Defaults']['repeat, rotate-right'] = array("class"=>'repeat rotate-right',"tags"=>'repeat,rotate-right',"unicode"=>'');
$icons['Defaults']['refresh'] = array("class"=>'refresh',"tags"=>'refresh',"unicode"=>'');
$icons['Defaults']['list-alt'] = array("class"=>'list-alt',"tags"=>'list-alt',"unicode"=>'');
$icons['Defaults']['lock'] = array("class"=>'lock',"tags"=>'lock',"unicode"=>'');
$icons['Defaults']['flag'] = array("class"=>'flag',"tags"=>'flag',"unicode"=>'');
$icons['Defaults']['headphones'] = array("class"=>'headphones',"tags"=>'headphones',"unicode"=>'');
$icons['Defaults']['volume-off'] = array("class"=>'volume-off',"tags"=>'volume-off',"unicode"=>'');
$icons['Defaults']['volume-down'] = array("class"=>'volume-down',"tags"=>'volume-down',"unicode"=>'');
$icons['Defaults']['volume-up'] = array("class"=>'volume-up',"tags"=>'volume-up',"unicode"=>'');
$icons['Defaults']['qrcode'] = array("class"=>'qrcode',"tags"=>'qrcode',"unicode"=>'');
$icons['Defaults']['barcode'] = array("class"=>'barcode',"tags"=>'barcode',"unicode"=>'');
$icons['Defaults']['tag'] = array("class"=>'tag',"tags"=>'tag',"unicode"=>'');
$icons['Defaults']['tags'] = array("class"=>'tags',"tags"=>'tags',"unicode"=>'');
$icons['Defaults']['book'] = array("class"=>'book',"tags"=>'book',"unicode"=>'');
$icons['Defaults']['bookmark'] = array("class"=>'bookmark',"tags"=>'bookmark',"unicode"=>'');
$icons['Defaults']['print'] = array("class"=>'print',"tags"=>'print',"unicode"=>'');
$icons['Defaults']['camera'] = array("class"=>'camera',"tags"=>'camera',"unicode"=>'');
$icons['Defaults']['font'] = array("class"=>'font',"tags"=>'font',"unicode"=>'');
$icons['Defaults']['bold'] = array("class"=>'bold',"tags"=>'bold',"unicode"=>'');
$icons['Defaults']['italic'] = array("class"=>'italic',"tags"=>'italic',"unicode"=>'');
$icons['Defaults']['text-height'] = array("class"=>'text-height',"tags"=>'text-height',"unicode"=>'');
$icons['Defaults']['text-width'] = array("class"=>'text-width',"tags"=>'text-width',"unicode"=>'');
$icons['Defaults']['align-left'] = array("class"=>'align-left',"tags"=>'align-left',"unicode"=>'');
$icons['Defaults']['align-center'] = array("class"=>'align-center',"tags"=>'align-center',"unicode"=>'');
$icons['Defaults']['align-right'] = array("class"=>'align-right',"tags"=>'align-right',"unicode"=>'');
$icons['Defaults']['align-justify'] = array("class"=>'align-justify',"tags"=>'align-justify',"unicode"=>'');
$icons['Defaults']['list'] = array("class"=>'list',"tags"=>'list',"unicode"=>'');
$icons['Defaults']['dedent, outdent'] = array("class"=>'dedent outdent',"tags"=>'dedent,outdent',"unicode"=>'');
$icons['Defaults']['indent'] = array("class"=>'indent',"tags"=>'indent',"unicode"=>'');
$icons['Defaults']['video-camera'] = array("class"=>'video-camera',"tags"=>'video-camera',"unicode"=>'');
$icons['Defaults']['image, photo, picture-o'] = array("class"=>'image photo picture-o',"tags"=>'image,photo,picture-o',"unicode"=>'');
$icons['Defaults']['pencil'] = array("class"=>'pencil',"tags"=>'pencil',"unicode"=>'');
$icons['Defaults']['map-marker'] = array("class"=>'map-marker',"tags"=>'map-marker',"unicode"=>'');
$icons['Defaults']['adjust'] = array("class"=>'adjust',"tags"=>'adjust',"unicode"=>'');
$icons['Defaults']['tint'] = array("class"=>'tint',"tags"=>'tint',"unicode"=>'');
$icons['Defaults']['edit, pencil-square-o'] = array("class"=>'edit pencil-square-o',"tags"=>'edit,pencil-square-o',"unicode"=>'');
$icons['Defaults']['share-square-o'] = array("class"=>'share-square-o',"tags"=>'share-square-o',"unicode"=>'');
$icons['Defaults']['check-square-o'] = array("class"=>'check-square-o',"tags"=>'check-square-o',"unicode"=>'');
$icons['Defaults']['arrows'] = array("class"=>'arrows',"tags"=>'arrows',"unicode"=>'');
$icons['Defaults']['step-backward'] = array("class"=>'step-backward',"tags"=>'step-backward',"unicode"=>'');
$icons['Defaults']['fast-backward'] = array("class"=>'fast-backward',"tags"=>'fast-backward',"unicode"=>'');
$icons['Defaults']['backward'] = array("class"=>'backward',"tags"=>'backward',"unicode"=>'');
$icons['Defaults']['play'] = array("class"=>'play',"tags"=>'play',"unicode"=>'');
$icons['Defaults']['pause'] = array("class"=>'pause',"tags"=>'pause',"unicode"=>'');
$icons['Defaults']['stop'] = array("class"=>'stop',"tags"=>'stop',"unicode"=>'');
$icons['Defaults']['forward'] = array("class"=>'forward',"tags"=>'forward',"unicode"=>'');
$icons['Defaults']['fast-forward'] = array("class"=>'fast-forward',"tags"=>'fast-forward',"unicode"=>'');
$icons['Defaults']['step-forward'] = array("class"=>'step-forward',"tags"=>'step-forward',"unicode"=>'');
$icons['Defaults']['eject'] = array("class"=>'eject',"tags"=>'eject',"unicode"=>'');
$icons['Defaults']['chevron-left'] = array("class"=>'chevron-left',"tags"=>'chevron-left',"unicode"=>'');
$icons['Defaults']['chevron-right'] = array("class"=>'chevron-right',"tags"=>'chevron-right',"unicode"=>'');
$icons['Defaults']['plus-circle'] = array("class"=>'plus-circle',"tags"=>'plus-circle',"unicode"=>'');
$icons['Defaults']['minus-circle'] = array("class"=>'minus-circle',"tags"=>'minus-circle',"unicode"=>'');
$icons['Defaults']['times-circle'] = array("class"=>'times-circle',"tags"=>'times-circle',"unicode"=>'');
$icons['Defaults']['check-circle'] = array("class"=>'check-circle',"tags"=>'check-circle',"unicode"=>'');
$icons['Defaults']['question-circle'] = array("class"=>'question-circle',"tags"=>'question-circle',"unicode"=>'');
$icons['Defaults']['info-circle'] = array("class"=>'info-circle',"tags"=>'info-circle',"unicode"=>'');
$icons['Defaults']['crosshairs'] = array("class"=>'crosshairs',"tags"=>'crosshairs',"unicode"=>'');
$icons['Defaults']['times-circle-o'] = array("class"=>'times-circle-o',"tags"=>'times-circle-o',"unicode"=>'');
$icons['Defaults']['check-circle-o'] = array("class"=>'check-circle-o',"tags"=>'check-circle-o',"unicode"=>'');
$icons['Defaults']['ban'] = array("class"=>'ban',"tags"=>'ban',"unicode"=>'');
$icons['Defaults']['arrow-left'] = array("class"=>'arrow-left',"tags"=>'arrow-left',"unicode"=>'');
$icons['Defaults']['arrow-right'] = array("class"=>'arrow-right',"tags"=>'arrow-right',"unicode"=>'');
$icons['Defaults']['arrow-up'] = array("class"=>'arrow-up',"tags"=>'arrow-up',"unicode"=>'');
$icons['Defaults']['arrow-down'] = array("class"=>'arrow-down',"tags"=>'arrow-down',"unicode"=>'');
$icons['Defaults']['mail-forward, share'] = array("class"=>'mail-forward share',"tags"=>'mail-forward,share',"unicode"=>'');
$icons['Defaults']['expand'] = array("class"=>'expand',"tags"=>'expand',"unicode"=>'');
$icons['Defaults']['compress'] = array("class"=>'compress',"tags"=>'compress',"unicode"=>'');
$icons['Defaults']['plus'] = array("class"=>'plus',"tags"=>'plus',"unicode"=>'');
$icons['Defaults']['minus'] = array("class"=>'minus',"tags"=>'minus',"unicode"=>'');
$icons['Defaults']['asterisk'] = array("class"=>'asterisk',"tags"=>'asterisk',"unicode"=>'');
$icons['Defaults']['exclamation-circle'] = array("class"=>'exclamation-circle',"tags"=>'exclamation-circle',"unicode"=>'');
$icons['Defaults']['gift'] = array("class"=>'gift',"tags"=>'gift',"unicode"=>'');
$icons['Defaults']['leaf'] = array("class"=>'leaf',"tags"=>'leaf',"unicode"=>'');
$icons['Defaults']['fire'] = array("class"=>'fire',"tags"=>'fire',"unicode"=>'');
$icons['Defaults']['eye'] = array("class"=>'eye',"tags"=>'eye',"unicode"=>'');
$icons['Defaults']['eye-slash'] = array("class"=>'eye-slash',"tags"=>'eye-slash',"unicode"=>'');
$icons['Defaults']['exclamation-triangle, warning'] = array("class"=>'exclamation-triangle warning',"tags"=>'exclamation-triangle,warning',"unicode"=>'');
$icons['Defaults']['plane'] = array("class"=>'plane',"tags"=>'plane',"unicode"=>'');
$icons['Defaults']['calendar'] = array("class"=>'calendar',"tags"=>'calendar',"unicode"=>'');
$icons['Defaults']['random'] = array("class"=>'random',"tags"=>'random',"unicode"=>'');
$icons['Defaults']['comment'] = array("class"=>'comment',"tags"=>'comment',"unicode"=>'');
$icons['Defaults']['magnet'] = array("class"=>'magnet',"tags"=>'magnet',"unicode"=>'');
$icons['Defaults']['chevron-up'] = array("class"=>'chevron-up',"tags"=>'chevron-up',"unicode"=>'');
$icons['Defaults']['chevron-down'] = array("class"=>'chevron-down',"tags"=>'chevron-down',"unicode"=>'');
$icons['Defaults']['retweet'] = array("class"=>'retweet',"tags"=>'retweet',"unicode"=>'');
$icons['Defaults']['shopping-cart'] = array("class"=>'shopping-cart',"tags"=>'shopping-cart',"unicode"=>'');
$icons['Defaults']['folder'] = array("class"=>'folder',"tags"=>'folder',"unicode"=>'');
$icons['Defaults']['folder-open'] = array("class"=>'folder-open',"tags"=>'folder-open',"unicode"=>'');
$icons['Defaults']['arrows-v'] = array("class"=>'arrows-v',"tags"=>'arrows-v',"unicode"=>'');
$icons['Defaults']['arrows-h'] = array("class"=>'arrows-h',"tags"=>'arrows-h',"unicode"=>'');
$icons['Defaults']['bar-chart, bar-chart-o'] = array("class"=>'bar-chart bar-chart-o',"tags"=>'bar-chart,bar-chart-o',"unicode"=>'');
$icons['Defaults']['twitter-square'] = array("class"=>'twitter-square',"tags"=>'twitter-square',"unicode"=>'');
$icons['Defaults']['facebook-square'] = array("class"=>'facebook-square',"tags"=>'facebook-square',"unicode"=>'');
$icons['Defaults']['camera-retro'] = array("class"=>'camera-retro',"tags"=>'camera-retro',"unicode"=>'');
$icons['Defaults']['key'] = array("class"=>'key',"tags"=>'key',"unicode"=>'');
$icons['Defaults']['cogs, gears'] = array("class"=>'cogs gears',"tags"=>'cogs,gears',"unicode"=>'');
$icons['Defaults']['comments'] = array("class"=>'comments',"tags"=>'comments',"unicode"=>'');
$icons['Defaults']['thumbs-o-up'] = array("class"=>'thumbs-o-up',"tags"=>'thumbs-o-up',"unicode"=>'');
$icons['Defaults']['thumbs-o-down'] = array("class"=>'thumbs-o-down',"tags"=>'thumbs-o-down',"unicode"=>'');
$icons['Defaults']['star-half'] = array("class"=>'star-half',"tags"=>'star-half',"unicode"=>'');
$icons['Defaults']['heart-o'] = array("class"=>'heart-o',"tags"=>'heart-o',"unicode"=>'');
$icons['Defaults']['sign-out'] = array("class"=>'sign-out',"tags"=>'sign-out',"unicode"=>'');
$icons['Defaults']['linkedin-square'] = array("class"=>'linkedin-square',"tags"=>'linkedin-square',"unicode"=>'');
$icons['Defaults']['thumb-tack'] = array("class"=>'thumb-tack',"tags"=>'thumb-tack',"unicode"=>'');
$icons['Defaults']['external-link'] = array("class"=>'external-link',"tags"=>'external-link',"unicode"=>'');
$icons['Defaults']['sign-in'] = array("class"=>'sign-in',"tags"=>'sign-in',"unicode"=>'');
$icons['Defaults']['trophy'] = array("class"=>'trophy',"tags"=>'trophy',"unicode"=>'');
$icons['Defaults']['github-square'] = array("class"=>'github-square',"tags"=>'github-square',"unicode"=>'');
$icons['Defaults']['upload'] = array("class"=>'upload',"tags"=>'upload',"unicode"=>'');
$icons['Defaults']['lemon-o'] = array("class"=>'lemon-o',"tags"=>'lemon-o',"unicode"=>'');
$icons['Defaults']['phone'] = array("class"=>'phone',"tags"=>'phone',"unicode"=>'');
$icons['Defaults']['square-o'] = array("class"=>'square-o',"tags"=>'square-o',"unicode"=>'');
$icons['Defaults']['bookmark-o'] = array("class"=>'bookmark-o',"tags"=>'bookmark-o',"unicode"=>'');
$icons['Defaults']['phone-square'] = array("class"=>'phone-square',"tags"=>'phone-square',"unicode"=>'');
$icons['Defaults']['twitter'] = array("class"=>'twitter',"tags"=>'twitter',"unicode"=>'');
$icons['Defaults']['facebook, facebook-f'] = array("class"=>'facebook facebook-f',"tags"=>'facebook,facebook-f',"unicode"=>'');
$icons['Defaults']['github'] = array("class"=>'github',"tags"=>'github',"unicode"=>'');
$icons['Defaults']['unlock'] = array("class"=>'unlock',"tags"=>'unlock',"unicode"=>'');
$icons['Defaults']['credit-card'] = array("class"=>'credit-card',"tags"=>'credit-card',"unicode"=>'');
$icons['Defaults']['rss'] = array("class"=>'rss',"tags"=>'rss',"unicode"=>'');
$icons['Defaults']['hdd-o'] = array("class"=>'hdd-o',"tags"=>'hdd-o',"unicode"=>'');
$icons['Defaults']['bullhorn'] = array("class"=>'bullhorn',"tags"=>'bullhorn',"unicode"=>'');
$icons['Defaults']['bell-o'] = array("class"=>'bell-o',"tags"=>'bell-o',"unicode"=>'');
$icons['Defaults']['certificate'] = array("class"=>'certificate',"tags"=>'certificate',"unicode"=>'');
$icons['Defaults']['hand-o-right'] = array("class"=>'hand-o-right',"tags"=>'hand-o-right',"unicode"=>'');
$icons['Defaults']['hand-o-left'] = array("class"=>'hand-o-left',"tags"=>'hand-o-left',"unicode"=>'');
$icons['Defaults']['hand-o-up'] = array("class"=>'hand-o-up',"tags"=>'hand-o-up',"unicode"=>'');
$icons['Defaults']['hand-o-down'] = array("class"=>'hand-o-down',"tags"=>'hand-o-down',"unicode"=>'');
$icons['Defaults']['arrow-circle-left'] = array("class"=>'arrow-circle-left',"tags"=>'arrow-circle-left',"unicode"=>'');
$icons['Defaults']['arrow-circle-right'] = array("class"=>'arrow-circle-right',"tags"=>'arrow-circle-right',"unicode"=>'');
$icons['Defaults']['arrow-circle-up'] = array("class"=>'arrow-circle-up',"tags"=>'arrow-circle-up',"unicode"=>'');
$icons['Defaults']['arrow-circle-down'] = array("class"=>'arrow-circle-down',"tags"=>'arrow-circle-down',"unicode"=>'');
$icons['Defaults']['globe'] = array("class"=>'globe',"tags"=>'globe',"unicode"=>'');
$icons['Defaults']['wrench'] = array("class"=>'wrench',"tags"=>'wrench',"unicode"=>'');
$icons['Defaults']['tasks'] = array("class"=>'tasks',"tags"=>'tasks',"unicode"=>'');
$icons['Defaults']['filter'] = array("class"=>'filter',"tags"=>'filter',"unicode"=>'');
$icons['Defaults']['briefcase'] = array("class"=>'briefcase',"tags"=>'briefcase',"unicode"=>'');
$icons['Defaults']['arrows-alt'] = array("class"=>'arrows-alt',"tags"=>'arrows-alt',"unicode"=>'');
$icons['Defaults']['group, users'] = array("class"=>'group users',"tags"=>'group,users',"unicode"=>'');
$icons['Defaults']['chain, link'] = array("class"=>'chain link',"tags"=>'chain,link',"unicode"=>'');
$icons['Defaults']['cloud'] = array("class"=>'cloud',"tags"=>'cloud',"unicode"=>'');
$icons['Defaults']['flask'] = array("class"=>'flask',"tags"=>'flask',"unicode"=>'');
$icons['Defaults']['cut, scissors'] = array("class"=>'cut scissors',"tags"=>'cut,scissors',"unicode"=>'');
$icons['Defaults']['copy, files-o'] = array("class"=>'copy files-o',"tags"=>'copy,files-o',"unicode"=>'');
$icons['Defaults']['paperclip'] = array("class"=>'paperclip',"tags"=>'paperclip',"unicode"=>'');
$icons['Defaults']['floppy-o, save'] = array("class"=>'floppy-o save',"tags"=>'floppy-o,save',"unicode"=>'');
$icons['Defaults']['square'] = array("class"=>'square',"tags"=>'square',"unicode"=>'');
$icons['Defaults']['bars, navicon, reorder'] = array("class"=>'bars navicon reorder',"tags"=>'bars,navicon,reorder',"unicode"=>'');
$icons['Defaults']['list-ul'] = array("class"=>'list-ul',"tags"=>'list-ul',"unicode"=>'');
$icons['Defaults']['list-ol'] = array("class"=>'list-ol',"tags"=>'list-ol',"unicode"=>'');
$icons['Defaults']['strikethrough'] = array("class"=>'strikethrough',"tags"=>'strikethrough',"unicode"=>'');
$icons['Defaults']['underline'] = array("class"=>'underline',"tags"=>'underline',"unicode"=>'');
$icons['Defaults']['table'] = array("class"=>'table',"tags"=>'table',"unicode"=>'');
$icons['Defaults']['magic'] = array("class"=>'magic',"tags"=>'magic',"unicode"=>'');
$icons['Defaults']['truck'] = array("class"=>'truck',"tags"=>'truck',"unicode"=>'');
$icons['Defaults']['pinterest'] = array("class"=>'pinterest',"tags"=>'pinterest',"unicode"=>'');
$icons['Defaults']['pinterest-square'] = array("class"=>'pinterest-square',"tags"=>'pinterest-square',"unicode"=>'');
$icons['Defaults']['google-plus-square'] = array("class"=>'google-plus-square',"tags"=>'google-plus-square',"unicode"=>'');
$icons['Defaults']['google-plus'] = array("class"=>'google-plus',"tags"=>'google-plus',"unicode"=>'');
$icons['Defaults']['money'] = array("class"=>'money',"tags"=>'money',"unicode"=>'');
$icons['Defaults']['caret-down'] = array("class"=>'caret-down',"tags"=>'caret-down',"unicode"=>'');
$icons['Defaults']['caret-up'] = array("class"=>'caret-up',"tags"=>'caret-up',"unicode"=>'');
$icons['Defaults']['caret-left'] = array("class"=>'caret-left',"tags"=>'caret-left',"unicode"=>'');
$icons['Defaults']['caret-right'] = array("class"=>'caret-right',"tags"=>'caret-right',"unicode"=>'');
$icons['Defaults']['columns'] = array("class"=>'columns',"tags"=>'columns',"unicode"=>'');
$icons['Defaults']['sort, unsorted'] = array("class"=>'sort unsorted',"tags"=>'sort,unsorted',"unicode"=>'');
$icons['Defaults']['sort-desc, sort-down'] = array("class"=>'sort-desc sort-down',"tags"=>'sort-desc,sort-down',"unicode"=>'');
$icons['Defaults']['sort-asc, sort-up'] = array("class"=>'sort-asc sort-up',"tags"=>'sort-asc,sort-up',"unicode"=>'');
$icons['Defaults']['envelope'] = array("class"=>'envelope',"tags"=>'envelope',"unicode"=>'');
$icons['Defaults']['linkedin'] = array("class"=>'linkedin',"tags"=>'linkedin',"unicode"=>'');
$icons['Defaults']['rotate-left, undo'] = array("class"=>'rotate-left undo',"tags"=>'rotate-left,undo',"unicode"=>'');
$icons['Defaults']['gavel, legal'] = array("class"=>'gavel legal',"tags"=>'gavel,legal',"unicode"=>'');
$icons['Defaults']['dashboard, tachometer'] = array("class"=>'dashboard tachometer',"tags"=>'dashboard,tachometer',"unicode"=>'');
$icons['Defaults']['comment-o'] = array("class"=>'comment-o',"tags"=>'comment-o',"unicode"=>'');
$icons['Defaults']['comments-o'] = array("class"=>'comments-o',"tags"=>'comments-o',"unicode"=>'');
$icons['Defaults']['bolt, flash'] = array("class"=>'bolt flash',"tags"=>'bolt,flash',"unicode"=>'');
$icons['Defaults']['sitemap'] = array("class"=>'sitemap',"tags"=>'sitemap',"unicode"=>'');
$icons['Defaults']['umbrella'] = array("class"=>'umbrella',"tags"=>'umbrella',"unicode"=>'');
$icons['Defaults']['clipboard, paste'] = array("class"=>'clipboard paste',"tags"=>'clipboard,paste',"unicode"=>'');
$icons['Defaults']['lightbulb-o'] = array("class"=>'lightbulb-o',"tags"=>'lightbulb-o',"unicode"=>'');
$icons['Defaults']['exchange'] = array("class"=>'exchange',"tags"=>'exchange',"unicode"=>'');
$icons['Defaults']['cloud-download'] = array("class"=>'cloud-download',"tags"=>'cloud-download',"unicode"=>'');
$icons['Defaults']['cloud-upload'] = array("class"=>'cloud-upload',"tags"=>'cloud-upload',"unicode"=>'');
$icons['Defaults']['user-md'] = array("class"=>'user-md',"tags"=>'user-md',"unicode"=>'');
$icons['Defaults']['stethoscope'] = array("class"=>'stethoscope',"tags"=>'stethoscope',"unicode"=>'');
$icons['Defaults']['suitcase'] = array("class"=>'suitcase',"tags"=>'suitcase',"unicode"=>'');
$icons['Defaults']['bell'] = array("class"=>'bell',"tags"=>'bell',"unicode"=>'');
$icons['Defaults']['coffee'] = array("class"=>'coffee',"tags"=>'coffee',"unicode"=>'');
$icons['Defaults']['cutlery'] = array("class"=>'cutlery',"tags"=>'cutlery',"unicode"=>'');
$icons['Defaults']['file-text-o'] = array("class"=>'file-text-o',"tags"=>'file-text-o',"unicode"=>'');
$icons['Defaults']['building-o'] = array("class"=>'building-o',"tags"=>'building-o',"unicode"=>'');
$icons['Defaults']['hospital-o'] = array("class"=>'hospital-o',"tags"=>'hospital-o',"unicode"=>'');
$icons['Defaults']['ambulance'] = array("class"=>'ambulance',"tags"=>'ambulance',"unicode"=>'');
$icons['Defaults']['medkit'] = array("class"=>'medkit',"tags"=>'medkit',"unicode"=>'');
$icons['Defaults']['fighter-jet'] = array("class"=>'fighter-jet',"tags"=>'fighter-jet',"unicode"=>'');
$icons['Defaults']['beer'] = array("class"=>'beer',"tags"=>'beer',"unicode"=>'');
$icons['Defaults']['h-square'] = array("class"=>'h-square',"tags"=>'h-square',"unicode"=>'');
$icons['Defaults']['plus-square'] = array("class"=>'plus-square',"tags"=>'plus-square',"unicode"=>'');
$icons['Defaults']['angle-double-left'] = array("class"=>'angle-double-left',"tags"=>'angle-double-left',"unicode"=>'');
$icons['Defaults']['angle-double-right'] = array("class"=>'angle-double-right',"tags"=>'angle-double-right',"unicode"=>'');
$icons['Defaults']['angle-double-up'] = array("class"=>'angle-double-up',"tags"=>'angle-double-up',"unicode"=>'');
$icons['Defaults']['angle-double-down'] = array("class"=>'angle-double-down',"tags"=>'angle-double-down',"unicode"=>'');
$icons['Defaults']['angle-left'] = array("class"=>'angle-left',"tags"=>'angle-left',"unicode"=>'');
$icons['Defaults']['angle-right'] = array("class"=>'angle-right',"tags"=>'angle-right',"unicode"=>'');
$icons['Defaults']['angle-up'] = array("class"=>'angle-up',"tags"=>'angle-up',"unicode"=>'');
$icons['Defaults']['angle-down'] = array("class"=>'angle-down',"tags"=>'angle-down',"unicode"=>'');
$icons['Defaults']['desktop'] = array("class"=>'desktop',"tags"=>'desktop',"unicode"=>'');
$icons['Defaults']['laptop'] = array("class"=>'laptop',"tags"=>'laptop',"unicode"=>'');
$icons['Defaults']['tablet'] = array("class"=>'tablet',"tags"=>'tablet',"unicode"=>'');
$icons['Defaults']['mobile, mobile-phone'] = array("class"=>'mobile mobile-phone',"tags"=>'mobile,mobile-phone',"unicode"=>'');
$icons['Defaults']['circle-o'] = array("class"=>'circle-o',"tags"=>'circle-o',"unicode"=>'');
$icons['Defaults']['quote-left'] = array("class"=>'quote-left',"tags"=>'quote-left',"unicode"=>'');
$icons['Defaults']['quote-right'] = array("class"=>'quote-right',"tags"=>'quote-right',"unicode"=>'');
$icons['Defaults']['spinner'] = array("class"=>'spinner',"tags"=>'spinner',"unicode"=>'');
$icons['Defaults']['circle'] = array("class"=>'circle',"tags"=>'circle',"unicode"=>'');
$icons['Defaults']['mail-reply, reply'] = array("class"=>'mail-reply reply',"tags"=>'mail-reply,reply',"unicode"=>'');
$icons['Defaults']['github-alt'] = array("class"=>'github-alt',"tags"=>'github-alt',"unicode"=>'');
$icons['Defaults']['folder-o'] = array("class"=>'folder-o',"tags"=>'folder-o',"unicode"=>'');
$icons['Defaults']['folder-open-o'] = array("class"=>'folder-open-o',"tags"=>'folder-open-o',"unicode"=>'');
$icons['Defaults']['smile-o'] = array("class"=>'smile-o',"tags"=>'smile-o',"unicode"=>'');
$icons['Defaults']['frown-o'] = array("class"=>'frown-o',"tags"=>'frown-o',"unicode"=>'');
$icons['Defaults']['meh-o'] = array("class"=>'meh-o',"tags"=>'meh-o',"unicode"=>'');
$icons['Defaults']['gamepad'] = array("class"=>'gamepad',"tags"=>'gamepad',"unicode"=>'');
$icons['Defaults']['keyboard-o'] = array("class"=>'keyboard-o',"tags"=>'keyboard-o',"unicode"=>'');
$icons['Defaults']['flag-o'] = array("class"=>'flag-o',"tags"=>'flag-o',"unicode"=>'');
$icons['Defaults']['flag-checkered'] = array("class"=>'flag-checkered',"tags"=>'flag-checkered',"unicode"=>'');
$icons['Defaults']['terminal'] = array("class"=>'terminal',"tags"=>'terminal',"unicode"=>'');
$icons['Defaults']['code'] = array("class"=>'code',"tags"=>'code',"unicode"=>'');
$icons['Defaults']['mail-reply-all, reply-all'] = array("class"=>'mail-reply-all reply-all',"tags"=>'mail-reply-all,reply-all',"unicode"=>'');
$icons['Defaults']['star-half-empty, star-half-full, star-half-o'] = array("class"=>'star-half-empty star-half-full star-half-o',"tags"=>'star-half-empty,star-half-full,star-half-o',"unicode"=>'');
$icons['Defaults']['location-arrow'] = array("class"=>'location-arrow',"tags"=>'location-arrow',"unicode"=>'');
$icons['Defaults']['crop'] = array("class"=>'crop',"tags"=>'crop',"unicode"=>'');
$icons['Defaults']['code-fork'] = array("class"=>'code-fork',"tags"=>'code-fork',"unicode"=>'');
$icons['Defaults']['chain-broken, unlink'] = array("class"=>'chain-broken unlink',"tags"=>'chain-broken,unlink',"unicode"=>'');
$icons['Defaults']['question'] = array("class"=>'question',"tags"=>'question',"unicode"=>'');
$icons['Defaults']['info'] = array("class"=>'info',"tags"=>'info',"unicode"=>'');
$icons['Defaults']['exclamation'] = array("class"=>'exclamation',"tags"=>'exclamation',"unicode"=>'');
$icons['Defaults']['superscript'] = array("class"=>'superscript',"tags"=>'superscript',"unicode"=>'');
$icons['Defaults']['subscript'] = array("class"=>'subscript',"tags"=>'subscript',"unicode"=>'');
$icons['Defaults']['eraser'] = array("class"=>'eraser',"tags"=>'eraser',"unicode"=>'');
$icons['Defaults']['puzzle-piece'] = array("class"=>'puzzle-piece',"tags"=>'puzzle-piece',"unicode"=>'');
$icons['Defaults']['microphone'] = array("class"=>'microphone',"tags"=>'microphone',"unicode"=>'');
$icons['Defaults']['microphone-slash'] = array("class"=>'microphone-slash',"tags"=>'microphone-slash',"unicode"=>'');
$icons['Defaults']['shield'] = array("class"=>'shield',"tags"=>'shield',"unicode"=>'');
$icons['Defaults']['calendar-o'] = array("class"=>'calendar-o',"tags"=>'calendar-o',"unicode"=>'');
$icons['Defaults']['fire-extinguisher'] = array("class"=>'fire-extinguisher',"tags"=>'fire-extinguisher',"unicode"=>'');
$icons['Defaults']['rocket'] = array("class"=>'rocket',"tags"=>'rocket',"unicode"=>'');
$icons['Defaults']['maxcdn'] = array("class"=>'maxcdn',"tags"=>'maxcdn',"unicode"=>'');
$icons['Defaults']['chevron-circle-left'] = array("class"=>'chevron-circle-left',"tags"=>'chevron-circle-left',"unicode"=>'');
$icons['Defaults']['chevron-circle-right'] = array("class"=>'chevron-circle-right',"tags"=>'chevron-circle-right',"unicode"=>'');
$icons['Defaults']['chevron-circle-up'] = array("class"=>'chevron-circle-up',"tags"=>'chevron-circle-up',"unicode"=>'');
$icons['Defaults']['chevron-circle-down'] = array("class"=>'chevron-circle-down',"tags"=>'chevron-circle-down',"unicode"=>'');
$icons['Defaults']['html5'] = array("class"=>'html5',"tags"=>'html5',"unicode"=>'');
$icons['Defaults']['css3'] = array("class"=>'css3',"tags"=>'css3',"unicode"=>'');
$icons['Defaults']['anchor'] = array("class"=>'anchor',"tags"=>'anchor',"unicode"=>'');
$icons['Defaults']['unlock-alt'] = array("class"=>'unlock-alt',"tags"=>'unlock-alt',"unicode"=>'');
$icons['Defaults']['bullseye'] = array("class"=>'bullseye',"tags"=>'bullseye',"unicode"=>'');
$icons['Defaults']['ellipsis-h'] = array("class"=>'ellipsis-h',"tags"=>'ellipsis-h',"unicode"=>'');
$icons['Defaults']['ellipsis-v'] = array("class"=>'ellipsis-v',"tags"=>'ellipsis-v',"unicode"=>'');
$icons['Defaults']['rss-square'] = array("class"=>'rss-square',"tags"=>'rss-square',"unicode"=>'');
$icons['Defaults']['play-circle'] = array("class"=>'play-circle',"tags"=>'play-circle',"unicode"=>'');
$icons['Defaults']['ticket'] = array("class"=>'ticket',"tags"=>'ticket',"unicode"=>'');
$icons['Defaults']['minus-square'] = array("class"=>'minus-square',"tags"=>'minus-square',"unicode"=>'');
$icons['Defaults']['minus-square-o'] = array("class"=>'minus-square-o',"tags"=>'minus-square-o',"unicode"=>'');
$icons['Defaults']['level-up'] = array("class"=>'level-up',"tags"=>'level-up',"unicode"=>'');
$icons['Defaults']['level-down'] = array("class"=>'level-down',"tags"=>'level-down',"unicode"=>'');
$icons['Defaults']['check-square'] = array("class"=>'check-square',"tags"=>'check-square',"unicode"=>'');
$icons['Defaults']['pencil-square'] = array("class"=>'pencil-square',"tags"=>'pencil-square',"unicode"=>'');
$icons['Defaults']['external-link-square'] = array("class"=>'external-link-square',"tags"=>'external-link-square',"unicode"=>'');
$icons['Defaults']['share-square'] = array("class"=>'share-square',"tags"=>'share-square',"unicode"=>'');
$icons['Defaults']['compass'] = array("class"=>'compass',"tags"=>'compass',"unicode"=>'');
$icons['Defaults']['caret-square-o-down, toggle-down'] = array("class"=>'caret-square-o-down toggle-down',"tags"=>'caret-square-o-down,toggle-down',"unicode"=>'');
$icons['Defaults']['caret-square-o-up, toggle-up'] = array("class"=>'caret-square-o-up toggle-up',"tags"=>'caret-square-o-up,toggle-up',"unicode"=>'');
$icons['Defaults']['caret-square-o-right, toggle-right'] = array("class"=>'caret-square-o-right toggle-right',"tags"=>'caret-square-o-right,toggle-right',"unicode"=>'');
$icons['Defaults']['eur, euro'] = array("class"=>'eur euro',"tags"=>'eur,euro',"unicode"=>'');
$icons['Defaults']['gbp'] = array("class"=>'gbp',"tags"=>'gbp',"unicode"=>'');
$icons['Defaults']['dollar, usd'] = array("class"=>'dollar usd',"tags"=>'dollar,usd',"unicode"=>'');
$icons['Defaults']['inr, rupee'] = array("class"=>'inr rupee',"tags"=>'inr,rupee',"unicode"=>'');
$icons['Defaults']['cny, jpy, rmb, yen'] = array("class"=>'cny jpy rmb yen',"tags"=>'cny,jpy,rmb,yen',"unicode"=>'');
$icons['Defaults']['rouble, rub, ruble'] = array("class"=>'rouble rub ruble',"tags"=>'rouble,rub,ruble',"unicode"=>'');
$icons['Defaults']['krw, won'] = array("class"=>'krw won',"tags"=>'krw,won',"unicode"=>'');
$icons['Defaults']['bitcoin, btc'] = array("class"=>'bitcoin btc',"tags"=>'bitcoin,btc',"unicode"=>'');
$icons['Defaults']['file'] = array("class"=>'file',"tags"=>'file',"unicode"=>'');
$icons['Defaults']['file-text'] = array("class"=>'file-text',"tags"=>'file-text',"unicode"=>'');
$icons['Defaults']['sort-alpha-asc'] = array("class"=>'sort-alpha-asc',"tags"=>'sort-alpha-asc',"unicode"=>'');
$icons['Defaults']['sort-alpha-desc'] = array("class"=>'sort-alpha-desc',"tags"=>'sort-alpha-desc',"unicode"=>'');
$icons['Defaults']['sort-amount-asc'] = array("class"=>'sort-amount-asc',"tags"=>'sort-amount-asc',"unicode"=>'');
$icons['Defaults']['sort-amount-desc'] = array("class"=>'sort-amount-desc',"tags"=>'sort-amount-desc',"unicode"=>'');
$icons['Defaults']['sort-numeric-asc'] = array("class"=>'sort-numeric-asc',"tags"=>'sort-numeric-asc',"unicode"=>'');
$icons['Defaults']['sort-numeric-desc'] = array("class"=>'sort-numeric-desc',"tags"=>'sort-numeric-desc',"unicode"=>'');
$icons['Defaults']['thumbs-up'] = array("class"=>'thumbs-up',"tags"=>'thumbs-up',"unicode"=>'');
$icons['Defaults']['thumbs-down'] = array("class"=>'thumbs-down',"tags"=>'thumbs-down',"unicode"=>'');
$icons['Defaults']['youtube-square'] = array("class"=>'youtube-square',"tags"=>'youtube-square',"unicode"=>'');
$icons['Defaults']['youtube'] = array("class"=>'youtube',"tags"=>'youtube',"unicode"=>'');
$icons['Defaults']['xing'] = array("class"=>'xing',"tags"=>'xing',"unicode"=>'');
$icons['Defaults']['xing-square'] = array("class"=>'xing-square',"tags"=>'xing-square',"unicode"=>'');
$icons['Defaults']['youtube-play'] = array("class"=>'youtube-play',"tags"=>'youtube-play',"unicode"=>'');
$icons['Defaults']['dropbox'] = array("class"=>'dropbox',"tags"=>'dropbox',"unicode"=>'');
$icons['Defaults']['stack-overflow'] = array("class"=>'stack-overflow',"tags"=>'stack-overflow',"unicode"=>'');
$icons['Defaults']['instagram'] = array("class"=>'instagram',"tags"=>'instagram',"unicode"=>'');
$icons['Defaults']['flickr'] = array("class"=>'flickr',"tags"=>'flickr',"unicode"=>'');
$icons['Defaults']['adn'] = array("class"=>'adn',"tags"=>'adn',"unicode"=>'');
$icons['Defaults']['bitbucket'] = array("class"=>'bitbucket',"tags"=>'bitbucket',"unicode"=>'');
$icons['Defaults']['bitbucket-square'] = array("class"=>'bitbucket-square',"tags"=>'bitbucket-square',"unicode"=>'');
$icons['Defaults']['tumblr'] = array("class"=>'tumblr',"tags"=>'tumblr',"unicode"=>'');
$icons['Defaults']['tumblr-square'] = array("class"=>'tumblr-square',"tags"=>'tumblr-square',"unicode"=>'');
$icons['Defaults']['long-arrow-down'] = array("class"=>'long-arrow-down',"tags"=>'long-arrow-down',"unicode"=>'');
$icons['Defaults']['long-arrow-up'] = array("class"=>'long-arrow-up',"tags"=>'long-arrow-up',"unicode"=>'');
$icons['Defaults']['long-arrow-left'] = array("class"=>'long-arrow-left',"tags"=>'long-arrow-left',"unicode"=>'');
$icons['Defaults']['long-arrow-right'] = array("class"=>'long-arrow-right',"tags"=>'long-arrow-right',"unicode"=>'');
$icons['Defaults']['apple'] = array("class"=>'apple',"tags"=>'apple',"unicode"=>'');
$icons['Defaults']['windows'] = array("class"=>'windows',"tags"=>'windows',"unicode"=>'');
$icons['Defaults']['android'] = array("class"=>'android',"tags"=>'android',"unicode"=>'');
$icons['Defaults']['linux'] = array("class"=>'linux',"tags"=>'linux',"unicode"=>'');
$icons['Defaults']['dribbble'] = array("class"=>'dribbble',"tags"=>'dribbble',"unicode"=>'');
$icons['Defaults']['skype'] = array("class"=>'skype',"tags"=>'skype',"unicode"=>'');
$icons['Defaults']['foursquare'] = array("class"=>'foursquare',"tags"=>'foursquare',"unicode"=>'');
$icons['Defaults']['trello'] = array("class"=>'trello',"tags"=>'trello',"unicode"=>'');
$icons['Defaults']['female'] = array("class"=>'female',"tags"=>'female',"unicode"=>'');
$icons['Defaults']['male'] = array("class"=>'male',"tags"=>'male',"unicode"=>'');
$icons['Defaults']['gittip, gratipay'] = array("class"=>'gittip gratipay',"tags"=>'gittip,gratipay',"unicode"=>'');
$icons['Defaults']['sun-o'] = array("class"=>'sun-o',"tags"=>'sun-o',"unicode"=>'');
$icons['Defaults']['moon-o'] = array("class"=>'moon-o',"tags"=>'moon-o',"unicode"=>'');
$icons['Defaults']['archive'] = array("class"=>'archive',"tags"=>'archive',"unicode"=>'');
$icons['Defaults']['bug'] = array("class"=>'bug',"tags"=>'bug',"unicode"=>'');
$icons['Defaults']['vk'] = array("class"=>'vk',"tags"=>'vk',"unicode"=>'');
$icons['Defaults']['weibo'] = array("class"=>'weibo',"tags"=>'weibo',"unicode"=>'');
$icons['Defaults']['renren'] = array("class"=>'renren',"tags"=>'renren',"unicode"=>'');
$icons['Defaults']['pagelines'] = array("class"=>'pagelines',"tags"=>'pagelines',"unicode"=>'');
$icons['Defaults']['stack-exchange'] = array("class"=>'stack-exchange',"tags"=>'stack-exchange',"unicode"=>'');
$icons['Defaults']['arrow-circle-o-right'] = array("class"=>'arrow-circle-o-right',"tags"=>'arrow-circle-o-right',"unicode"=>'');
$icons['Defaults']['arrow-circle-o-left'] = array("class"=>'arrow-circle-o-left',"tags"=>'arrow-circle-o-left',"unicode"=>'');
$icons['Defaults']['caret-square-o-left, toggle-left'] = array("class"=>'caret-square-o-left toggle-left',"tags"=>'caret-square-o-left,toggle-left',"unicode"=>'');
$icons['Defaults']['dot-circle-o'] = array("class"=>'dot-circle-o',"tags"=>'dot-circle-o',"unicode"=>'');
$icons['Defaults']['wheelchair'] = array("class"=>'wheelchair',"tags"=>'wheelchair',"unicode"=>'');
$icons['Defaults']['vimeo-square'] = array("class"=>'vimeo-square',"tags"=>'vimeo-square',"unicode"=>'');
$icons['Defaults']['try, turkish-lira'] = array("class"=>'try turkish-lira',"tags"=>'try,turkish-lira',"unicode"=>'');
$icons['Defaults']['plus-square-o'] = array("class"=>'plus-square-o',"tags"=>'plus-square-o',"unicode"=>'');
$icons['Defaults']['space-shuttle'] = array("class"=>'space-shuttle',"tags"=>'space-shuttle',"unicode"=>'');
$icons['Defaults']['slack'] = array("class"=>'slack',"tags"=>'slack',"unicode"=>'');
$icons['Defaults']['envelope-square'] = array("class"=>'envelope-square',"tags"=>'envelope-square',"unicode"=>'');
$icons['Defaults']['wordpress'] = array("class"=>'wordpress',"tags"=>'wordpress',"unicode"=>'');
$icons['Defaults']['openid'] = array("class"=>'openid',"tags"=>'openid',"unicode"=>'');
$icons['Defaults']['bank, institution, university'] = array("class"=>'bank institution university',"tags"=>'bank,institution,university',"unicode"=>'');
$icons['Defaults']['graduation-cap, mortar-board'] = array("class"=>'graduation-cap mortar-board',"tags"=>'graduation-cap,mortar-board',"unicode"=>'');
$icons['Defaults']['yahoo'] = array("class"=>'yahoo',"tags"=>'yahoo',"unicode"=>'');
$icons['Defaults']['google'] = array("class"=>'google',"tags"=>'google',"unicode"=>'');
$icons['Defaults']['reddit'] = array("class"=>'reddit',"tags"=>'reddit',"unicode"=>'');
$icons['Defaults']['reddit-square'] = array("class"=>'reddit-square',"tags"=>'reddit-square',"unicode"=>'');
$icons['Defaults']['stumbleupon-circle'] = array("class"=>'stumbleupon-circle',"tags"=>'stumbleupon-circle',"unicode"=>'');
$icons['Defaults']['stumbleupon'] = array("class"=>'stumbleupon',"tags"=>'stumbleupon',"unicode"=>'');
$icons['Defaults']['delicious'] = array("class"=>'delicious',"tags"=>'delicious',"unicode"=>'');
$icons['Defaults']['digg'] = array("class"=>'digg',"tags"=>'digg',"unicode"=>'');
$icons['Defaults']['pied-piper'] = array("class"=>'pied-piper',"tags"=>'pied-piper',"unicode"=>'');
$icons['Defaults']['pied-piper-alt'] = array("class"=>'pied-piper-alt',"tags"=>'pied-piper-alt',"unicode"=>'');
$icons['Defaults']['drupal'] = array("class"=>'drupal',"tags"=>'drupal',"unicode"=>'');
$icons['Defaults']['joomla'] = array("class"=>'joomla',"tags"=>'joomla',"unicode"=>'');
$icons['Defaults']['language'] = array("class"=>'language',"tags"=>'language',"unicode"=>'');
$icons['Defaults']['fax'] = array("class"=>'fax',"tags"=>'fax',"unicode"=>'');
$icons['Defaults']['building'] = array("class"=>'building',"tags"=>'building',"unicode"=>'');
$icons['Defaults']['child'] = array("class"=>'child',"tags"=>'child',"unicode"=>'');
$icons['Defaults']['paw'] = array("class"=>'paw',"tags"=>'paw',"unicode"=>'');
$icons['Defaults']['spoon'] = array("class"=>'spoon',"tags"=>'spoon',"unicode"=>'');
$icons['Defaults']['cube'] = array("class"=>'cube',"tags"=>'cube',"unicode"=>'');
$icons['Defaults']['cubes'] = array("class"=>'cubes',"tags"=>'cubes',"unicode"=>'');
$icons['Defaults']['behance'] = array("class"=>'behance',"tags"=>'behance',"unicode"=>'');
$icons['Defaults']['behance-square'] = array("class"=>'behance-square',"tags"=>'behance-square',"unicode"=>'');
$icons['Defaults']['steam'] = array("class"=>'steam',"tags"=>'steam',"unicode"=>'');
$icons['Defaults']['steam-square'] = array("class"=>'steam-square',"tags"=>'steam-square',"unicode"=>'');
$icons['Defaults']['recycle'] = array("class"=>'recycle',"tags"=>'recycle',"unicode"=>'');
$icons['Defaults']['automobile, car'] = array("class"=>'automobile car',"tags"=>'automobile,car',"unicode"=>'');
$icons['Defaults']['cab, taxi'] = array("class"=>'cab taxi',"tags"=>'cab,taxi',"unicode"=>'');
$icons['Defaults']['tree'] = array("class"=>'tree',"tags"=>'tree',"unicode"=>'');
$icons['Defaults']['spotify'] = array("class"=>'spotify',"tags"=>'spotify',"unicode"=>'');
$icons['Defaults']['deviantart'] = array("class"=>'deviantart',"tags"=>'deviantart',"unicode"=>'');
$icons['Defaults']['soundcloud'] = array("class"=>'soundcloud',"tags"=>'soundcloud',"unicode"=>'');
$icons['Defaults']['database'] = array("class"=>'database',"tags"=>'database',"unicode"=>'');
$icons['Defaults']['file-pdf-o'] = array("class"=>'file-pdf-o',"tags"=>'file-pdf-o',"unicode"=>'');
$icons['Defaults']['file-word-o'] = array("class"=>'file-word-o',"tags"=>'file-word-o',"unicode"=>'');
$icons['Defaults']['file-excel-o'] = array("class"=>'file-excel-o',"tags"=>'file-excel-o',"unicode"=>'');
$icons['Defaults']['file-powerpoint-o'] = array("class"=>'file-powerpoint-o',"tags"=>'file-powerpoint-o',"unicode"=>'');
$icons['Defaults']['file-image-o, file-photo-o, file-picture-o'] = array("class"=>'file-image-o file-photo-o file-picture-o',"tags"=>'file-image-o,file-photo-o,file-picture-o',"unicode"=>'');
$icons['Defaults']['file-archive-o, file-zip-o'] = array("class"=>'file-archive-o file-zip-o',"tags"=>'file-archive-o,file-zip-o',"unicode"=>'');
$icons['Defaults']['file-audio-o, file-sound-o'] = array("class"=>'file-audio-o file-sound-o',"tags"=>'file-audio-o,file-sound-o',"unicode"=>'');
$icons['Defaults']['file-movie-o, file-video-o'] = array("class"=>'file-movie-o file-video-o',"tags"=>'file-movie-o,file-video-o',"unicode"=>'');
$icons['Defaults']['file-code-o'] = array("class"=>'file-code-o',"tags"=>'file-code-o',"unicode"=>'');
$icons['Defaults']['vine'] = array("class"=>'vine',"tags"=>'vine',"unicode"=>'');
$icons['Defaults']['codepen'] = array("class"=>'codepen',"tags"=>'codepen',"unicode"=>'');
$icons['Defaults']['jsfiddle'] = array("class"=>'jsfiddle',"tags"=>'jsfiddle',"unicode"=>'');
$icons['Defaults']['life-bouy, life-buoy, life-ring, life-saver, support'] = array("class"=>'life-bouy life-buoy life-ring life-saver support',"tags"=>'life-bouy,life-buoy,life-ring,life-saver,support',"unicode"=>'');
$icons['Defaults']['circle-o-notch'] = array("class"=>'circle-o-notch',"tags"=>'circle-o-notch',"unicode"=>'');
$icons['Defaults']['ra, rebel'] = array("class"=>'ra rebel',"tags"=>'ra,rebel',"unicode"=>'');
$icons['Defaults']['empire, ge'] = array("class"=>'empire ge',"tags"=>'empire,ge',"unicode"=>'');
$icons['Defaults']['git-square'] = array("class"=>'git-square',"tags"=>'git-square',"unicode"=>'');
$icons['Defaults']['git'] = array("class"=>'git',"tags"=>'git',"unicode"=>'');
$icons['Defaults']['hacker-news'] = array("class"=>'hacker-news',"tags"=>'hacker-news',"unicode"=>'');
$icons['Defaults']['tencent-weibo'] = array("class"=>'tencent-weibo',"tags"=>'tencent-weibo',"unicode"=>'');
$icons['Defaults']['qq'] = array("class"=>'qq',"tags"=>'qq',"unicode"=>'');
$icons['Defaults']['wechat, weixin'] = array("class"=>'wechat weixin',"tags"=>'wechat,weixin',"unicode"=>'');
$icons['Defaults']['paper-plane, send'] = array("class"=>'paper-plane send',"tags"=>'paper-plane,send',"unicode"=>'');
$icons['Defaults']['paper-plane-o, send-o'] = array("class"=>'paper-plane-o send-o',"tags"=>'paper-plane-o,send-o',"unicode"=>'');
$icons['Defaults']['history'] = array("class"=>'history',"tags"=>'history',"unicode"=>'');
$icons['Defaults']['circle-thin, genderless'] = array("class"=>'circle-thin genderless',"tags"=>'circle-thin,genderless',"unicode"=>'');
$icons['Defaults']['header'] = array("class"=>'header',"tags"=>'header',"unicode"=>'');
$icons['Defaults']['paragraph'] = array("class"=>'paragraph',"tags"=>'paragraph',"unicode"=>'');
$icons['Defaults']['sliders'] = array("class"=>'sliders',"tags"=>'sliders',"unicode"=>'');
$icons['Defaults']['share-alt'] = array("class"=>'share-alt',"tags"=>'share-alt',"unicode"=>'');
$icons['Defaults']['share-alt-square'] = array("class"=>'share-alt-square',"tags"=>'share-alt-square',"unicode"=>'');
$icons['Defaults']['bomb'] = array("class"=>'bomb',"tags"=>'bomb',"unicode"=>'');
$icons['Defaults']['futbol-o, soccer-ball-o'] = array("class"=>'futbol-o soccer-ball-o',"tags"=>'futbol-o,soccer-ball-o',"unicode"=>'');
$icons['Defaults']['tty'] = array("class"=>'tty',"tags"=>'tty',"unicode"=>'');
$icons['Defaults']['binoculars'] = array("class"=>'binoculars',"tags"=>'binoculars',"unicode"=>'');
$icons['Defaults']['plug'] = array("class"=>'plug',"tags"=>'plug',"unicode"=>'');
$icons['Defaults']['slideshare'] = array("class"=>'slideshare',"tags"=>'slideshare',"unicode"=>'');
$icons['Defaults']['twitch'] = array("class"=>'twitch',"tags"=>'twitch',"unicode"=>'');
$icons['Defaults']['yelp'] = array("class"=>'yelp',"tags"=>'yelp',"unicode"=>'');
$icons['Defaults']['newspaper-o'] = array("class"=>'newspaper-o',"tags"=>'newspaper-o',"unicode"=>'');
$icons['Defaults']['wifi'] = array("class"=>'wifi',"tags"=>'wifi',"unicode"=>'');
$icons['Defaults']['calculator'] = array("class"=>'calculator',"tags"=>'calculator',"unicode"=>'');
$icons['Defaults']['paypal'] = array("class"=>'paypal',"tags"=>'paypal',"unicode"=>'');
$icons['Defaults']['google-wallet'] = array("class"=>'google-wallet',"tags"=>'google-wallet',"unicode"=>'');
$icons['Defaults']['cc-visa'] = array("class"=>'cc-visa',"tags"=>'cc-visa',"unicode"=>'');
$icons['Defaults']['cc-mastercard'] = array("class"=>'cc-mastercard',"tags"=>'cc-mastercard',"unicode"=>'');
$icons['Defaults']['cc-discover'] = array("class"=>'cc-discover',"tags"=>'cc-discover',"unicode"=>'');
$icons['Defaults']['cc-amex'] = array("class"=>'cc-amex',"tags"=>'cc-amex',"unicode"=>'');
$icons['Defaults']['cc-paypal'] = array("class"=>'cc-paypal',"tags"=>'cc-paypal',"unicode"=>'');
$icons['Defaults']['cc-stripe'] = array("class"=>'cc-stripe',"tags"=>'cc-stripe',"unicode"=>'');
$icons['Defaults']['bell-slash'] = array("class"=>'bell-slash',"tags"=>'bell-slash',"unicode"=>'');
$icons['Defaults']['bell-slash-o'] = array("class"=>'bell-slash-o',"tags"=>'bell-slash-o',"unicode"=>'');
$icons['Defaults']['trash'] = array("class"=>'trash',"tags"=>'trash',"unicode"=>'');
$icons['Defaults']['copyright'] = array("class"=>'copyright',"tags"=>'copyright',"unicode"=>'');
$icons['Defaults']['at'] = array("class"=>'at',"tags"=>'at',"unicode"=>'');
$icons['Defaults']['eyedropper'] = array("class"=>'eyedropper',"tags"=>'eyedropper',"unicode"=>'');
$icons['Defaults']['paint-brush'] = array("class"=>'paint-brush',"tags"=>'paint-brush',"unicode"=>'');
$icons['Defaults']['birthday-cake'] = array("class"=>'birthday-cake',"tags"=>'birthday-cake',"unicode"=>'');
$icons['Defaults']['area-chart'] = array("class"=>'area-chart',"tags"=>'area-chart',"unicode"=>'');
$icons['Defaults']['pie-chart'] = array("class"=>'pie-chart',"tags"=>'pie-chart',"unicode"=>'');
$icons['Defaults']['line-chart'] = array("class"=>'line-chart',"tags"=>'line-chart',"unicode"=>'');
$icons['Defaults']['lastfm'] = array("class"=>'lastfm',"tags"=>'lastfm',"unicode"=>'');
$icons['Defaults']['lastfm-square'] = array("class"=>'lastfm-square',"tags"=>'lastfm-square',"unicode"=>'');
$icons['Defaults']['toggle-off'] = array("class"=>'toggle-off',"tags"=>'toggle-off',"unicode"=>'');
$icons['Defaults']['toggle-on'] = array("class"=>'toggle-on',"tags"=>'toggle-on',"unicode"=>'');
$icons['Defaults']['bicycle'] = array("class"=>'bicycle',"tags"=>'bicycle',"unicode"=>'');
$icons['Defaults']['bus'] = array("class"=>'bus',"tags"=>'bus',"unicode"=>'');
$icons['Defaults']['ioxhost'] = array("class"=>'ioxhost',"tags"=>'ioxhost',"unicode"=>'');
$icons['Defaults']['angellist'] = array("class"=>'angellist',"tags"=>'angellist',"unicode"=>'');
$icons['Defaults']['cc'] = array("class"=>'cc',"tags"=>'cc',"unicode"=>'');
$icons['Defaults']['ils, shekel, sheqel'] = array("class"=>'ils shekel sheqel',"tags"=>'ils,shekel,sheqel',"unicode"=>'');
$icons['Defaults']['meanpath'] = array("class"=>'meanpath',"tags"=>'meanpath',"unicode"=>'');
$icons['Defaults']['buysellads'] = array("class"=>'buysellads',"tags"=>'buysellads',"unicode"=>'');
$icons['Defaults']['connectdevelop'] = array("class"=>'connectdevelop',"tags"=>'connectdevelop',"unicode"=>'');
$icons['Defaults']['dashcube'] = array("class"=>'dashcube',"tags"=>'dashcube',"unicode"=>'');
$icons['Defaults']['forumbee'] = array("class"=>'forumbee',"tags"=>'forumbee',"unicode"=>'');
$icons['Defaults']['leanpub'] = array("class"=>'leanpub',"tags"=>'leanpub',"unicode"=>'');
$icons['Defaults']['sellsy'] = array("class"=>'sellsy',"tags"=>'sellsy',"unicode"=>'');
$icons['Defaults']['shirtsinbulk'] = array("class"=>'shirtsinbulk',"tags"=>'shirtsinbulk',"unicode"=>'');
$icons['Defaults']['simplybuilt'] = array("class"=>'simplybuilt',"tags"=>'simplybuilt',"unicode"=>'');
$icons['Defaults']['skyatlas'] = array("class"=>'skyatlas',"tags"=>'skyatlas',"unicode"=>'');
$icons['Defaults']['cart-plus'] = array("class"=>'cart-plus',"tags"=>'cart-plus',"unicode"=>'');
$icons['Defaults']['cart-arrow-down'] = array("class"=>'cart-arrow-down',"tags"=>'cart-arrow-down',"unicode"=>'');
$icons['Defaults']['diamond'] = array("class"=>'diamond',"tags"=>'diamond',"unicode"=>'');
$icons['Defaults']['ship'] = array("class"=>'ship',"tags"=>'ship',"unicode"=>'');
$icons['Defaults']['user-secret'] = array("class"=>'user-secret',"tags"=>'user-secret',"unicode"=>'');
$icons['Defaults']['motorcycle'] = array("class"=>'motorcycle',"tags"=>'motorcycle',"unicode"=>'');
$icons['Defaults']['street-view'] = array("class"=>'street-view',"tags"=>'street-view',"unicode"=>'');
$icons['Defaults']['heartbeat'] = array("class"=>'heartbeat',"tags"=>'heartbeat',"unicode"=>'');
$icons['Defaults']['venus'] = array("class"=>'venus',"tags"=>'venus',"unicode"=>'');
$icons['Defaults']['mars'] = array("class"=>'mars',"tags"=>'mars',"unicode"=>'');
$icons['Defaults']['mercury'] = array("class"=>'mercury',"tags"=>'mercury',"unicode"=>'');
$icons['Defaults']['transgender'] = array("class"=>'transgender',"tags"=>'transgender',"unicode"=>'');
$icons['Defaults']['transgender-alt'] = array("class"=>'transgender-alt',"tags"=>'transgender-alt',"unicode"=>'');
$icons['Defaults']['venus-double'] = array("class"=>'venus-double',"tags"=>'venus-double',"unicode"=>'');
$icons['Defaults']['mars-double'] = array("class"=>'mars-double',"tags"=>'mars-double',"unicode"=>'');
$icons['Defaults']['venus-mars'] = array("class"=>'venus-mars',"tags"=>'venus-mars',"unicode"=>'');
$icons['Defaults']['mars-stroke'] = array("class"=>'mars-stroke',"tags"=>'mars-stroke',"unicode"=>'');
$icons['Defaults']['mars-stroke-v'] = array("class"=>'mars-stroke-v',"tags"=>'mars-stroke-v',"unicode"=>'');
$icons['Defaults']['mars-stroke-h'] = array("class"=>'mars-stroke-h',"tags"=>'mars-stroke-h',"unicode"=>'');
$icons['Defaults']['neuter'] = array("class"=>'neuter',"tags"=>'neuter',"unicode"=>'');
$icons['Defaults']['facebook-official'] = array("class"=>'facebook-official',"tags"=>'facebook-official',"unicode"=>'');
$icons['Defaults']['pinterest-p'] = array("class"=>'pinterest-p',"tags"=>'pinterest-p',"unicode"=>'');
$icons['Defaults']['whatsapp'] = array("class"=>'whatsapp',"tags"=>'whatsapp',"unicode"=>'');
$icons['Defaults']['server'] = array("class"=>'server',"tags"=>'server',"unicode"=>'');
$icons['Defaults']['user-plus'] = array("class"=>'user-plus',"tags"=>'user-plus',"unicode"=>'');
$icons['Defaults']['user-times'] = array("class"=>'user-times',"tags"=>'user-times',"unicode"=>'');
$icons['Defaults']['bed, hotel'] = array("class"=>'bed hotel',"tags"=>'bed,hotel',"unicode"=>'');
$icons['Defaults']['viacoin'] = array("class"=>'viacoin',"tags"=>'viacoin',"unicode"=>'');
$icons['Defaults']['train'] = array("class"=>'train',"tags"=>'train',"unicode"=>'');
$icons['Defaults']['subway'] = array("class"=>'subway',"tags"=>'subway',"unicode"=>'');
$icons['Defaults']['medium'] = array("class"=>'medium',"tags"=>'medium',"unicode"=>'');