<?php

/**
 * The admin-specific functionality of the plugin.
 *
 * @link       http://digital.wonderful.fr
 * @since      1.0.0
 *
 * @package    Wonderwp
 * @subpackage Wonderwp/admin
 */

namespace WonderWp\Plugin\Newsletter;

use WonderWp\APlugin\AbstractPluginBackendController;
use WonderWp\DI\Container;
use WonderWp\Templates\VueFrag;

/**
 * The admin-specific functionality of the plugin.
 *
 * Defines the plugin name, version, and two examples hooks for how to
 * enqueue the admin-specific stylesheet and JavaScript.
 *
 * @package    Wonderwp
 * @subpackage Wonderwp/admin
 * @author     Wonderful <jeremy.desvaux@wonderful.fr>
 */
class NewsletterAdminController extends AbstractPluginBackendController{

    public function getRoute()
    {
        $chosenPasserelle = '';
        if(empty($chosenPasserelle)){
            return 'options';
        } else {
            return parent::getRoute(); // TODO: Change the autogenerated stub
        }
    }

    public function customizeMenus(){

		//Add entry under top-level functionalities menu
		add_submenu_page('wonderwp-modules', 'Newsletter', 'Newsletter', $this->getMinCapability(), 'wwp-newsletter', array($this,'route'));

	}

    public function getTabs()
    {
        $tabs = array(
            1 => array('action' => 'list', 'libelle' => 'Listes de diffusion'),
            2 => array('action' => 'options', 'libelle' => 'Paramètres')
        );
        return $tabs;
    }

    public function optionsAction(){
        //Active tab should be Active Route
        //Vue should be simpler

        $container = Container::getInstance();
        $tabs = $this->getTabs();
        $vue = $container->offsetGet('wwp.basePlugin.backendView');
        $vue->addFrag(new VueFrag( $container->offsetGet($this->plugin_name.'.wwp.path.templates.frags.header'),array('title'=>get_admin_page_title())));
        if(!empty($tabs)){ $vue->addFrag(new VueFrag( $container->offsetGet($this->plugin_name.'.wwp.path.templates.frags.tabs'),array('tabs'=>$tabs))); }
        $vue->addFrag(new VueFrag( $container->offsetGet($this->plugin_name.'.wwp.path.templates.frags.footer')));
        $vue->render();
    }

}
