<?php
/**
 * Created by PhpStorm.
 * User: jeremydesvaux
 * Date: 26/08/2016
 * Time: 12:04
 */

namespace WonderWp\Theme;

use Pimple\Container as PContainer;
use WonderWp\APlugin\AbstractManager;

class ChildThemeManager extends ThemeManager
{

    public function register(PContainer $container)
    {
        parent::register($container); // TODO: Change the autogenerated stub
        //Routes
        $this->addService(AbstractManager::$ROUTESERVICENAME,function(){
            return new ThemeRouteService();
        });
        //Assets
        $this->addService(AbstractManager::$ASSETSSERVICENAME,function(){
            return new ThemeAssetService();
        });
    }

}